### ISSUE TITLE
error when running example.py

### ISSUE THREAD

**Issue by amiltonwong** [StanfordVL/MinkowskiEngine#1]
Hi, all,

I had followed the installation steps (conda virtual environment), and installed MinkowskiEngine successfully. However, when I run `python examples/example.py`, I got the following error:

```
Traceback (most recent call last):
  File "examples/example.py", line 5, in <module>
    import MinkowskiEngine as ME
  File "/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg/MinkowskiEngine/__init__.py", line 12, in <module>
    from SparseTensor import SparseTensor
  File "/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg/MinkowskiEngine/SparseTensor.py", line 6, in <module>
    from MinkowskiCoords import CoordsKey, CoordsManager
  File "/root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiCoords.py", line 4, in <module>
    import MinkowskiEngineBackend as MEB
ImportError: /root/anaconda3/envs/pytorch1.1/lib/python3.6/site-packages/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg/MinkowskiEngineBackend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cblas_dgemm
```

It seems something wrong or missing related to `cblas_dgemm`. Could you suggest me how to fix it?

THX!

PS. 
my system config:
ubuntu 16.04
python 3.6
pytorch 1.1

**Comment by chrischoy** [comment]
Thanks for reporting the issue.

Please follow the instruction and let me know the result?

1. Install `openblas` by `conda install openblas` in your environment.
2. edit line 33 of the  `Makefile` to `BLAS := open`.
3. edit line 62 of the `setup.py` to `libraries=['minkowski', 'openblas'],`
4. Go to the root directory of the MinkowskiEngine.
5. Type `make clean`
6. Type `python setup.py install`.

**Comment by chrischoy** [comment]
I submitted a fix for it.
Ignore the previous comment and follow the following instruction.


1. go to the root directory of the Minkowski Engine.
2. Type `git pull`
3. Type `make clean`
4. Type `python setup.py install`.

If it doesn't solve the issue, please let me know.

**Comment by chrischoy** [comment]
It seems like anaconda does not provide shared libraries for atlas. Since atlas is not actively maintained, I am switching to openblas. Also, anaconda provides shared libraries for it as well.

**Comment by amiltonwong** [comment]
@chrischoy , it works. Thanks a lot :)
