### ISSUE TITLE
How to use CPU-only MinkowskiEngine

### ISSUE THREAD

**Issue by jbjeong** [StanfordVL/MinkowskiEngine#10]
Hello, is it possible to use CPU-only MinkowskiEngine?
I want to use Sparse Convolution on my Macbook which has no CUDA.

When I tried to install MinkowskiEngine, I met this error.
`OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.`

Thanks!

**Comment by chrischoy** [comment]
I will work on it!

**Comment by chrischoy** [comment]
The commit ba646df4f2408ea449d7c4e05b3cf10fe4d452cb allows you to build with `CPU_ONLY` flag.

1. Uncomment line 8 of the Makefile
2. Uncomment line 66 of `setup.py`.
3. `python setup.py install`.
