### ISSUE TITLE
torch.range TypeError with pytorch v1.3

### ISSUE THREAD

**Issue by branislavhesko** [StanfordVL/MinkowskiEngine#101]
https://github.com/StanfordVL/MinkowskiEngine/blob/4aef10d2a1fbf3658282a0adcb6c0503b796de25/MinkowskiEngine/utils/quantization.py#L220

Hi Chris,
First of all, thanks for a great job about this framework. With the last version v0.4.1, I noticed 
torch.range with a single parameter. I think it throws TypeError with pytorch v1.3.
TypeError: range() missing 1 required positional arguments: "end"

A quick fix is to use arange instead of range, which is now deprecated.

Thanks.
Braňo

**Comment by chrischoy** [comment]
Thanks for reporting the issue. I just fixed it.
