### ISSUE TITLE
error run pointnet.py

### ISSUE THREAD

**Issue by rancheng** [StanfordVL/MinkowskiEngine#103]
The model inconsistency happens in multiple places, until now I still can not have a smooth run on the example of `pointnet.py`

I installed `minkowski==0.4.0` in my system with `CUDA 10.1`

https://github.com/StanfordVL/MinkowskiEngine/blob/a1fab7a14564d77245be57a9cc789e69f14c482a/examples/pointnet.py#L84-L88

here the error shows that the class `ME.MinkowskiInstanceNorm` doesn't have `dimension` argument.

But when navigate into file `MinkowskiEngine/MinkowskiInstanceNorm.py`

https://github.com/StanfordVL/MinkowskiEngine/blob/a1fab7a14564d77245be57a9cc789e69f14c482a/MinkowskiEngine/MinkowskiNormalization.py#L310-L318

There's still dimension here. I don't know why you delete this argument or will it break other models if we restore those arguments.

Another problem is that in here:

https://github.com/StanfordVL/MinkowskiEngine/blob/a1fab7a14564d77245be57a9cc789e69f14c482a/examples/pointnet.py#L82

Do you mean:

```python
self.broadcast = ME.MinkowskiBroadcastMultiplication()
```

and if so, your tensor should be reshaped into `3x3` rather than left as `1x9`

I have modified the code and I can open a pull request if it helps.

**Comment by chrischoy** [comment]
Thanks for submitting the issue.
I found a few problems with the code and it now works.

Please let me know if you have further questions.
