### ISSUE TITLE
Coordinates shuffled in tensor when accessed via coordinates_at(batch_index) [bug]

### ISSUE THREAD

**Issue by kumuji** [StanfordVL/MinkowskiEngine#119]
I was trying to get coordinates for visualization and had a problem where coordinates shuffled. Here is the code to reproduce the issue:
```
coordinates = torch.Tensor(
    np.hstack((np.zeros((5, 1)), (np.random.random((5, 3)) * 10)))
).int()
features = torch.Tensor(np.random.random((5, 3)))
```
Output for `coordinates` and `features`:
```
(tensor([[0, 3, 0, 7],
         [0, 1, 9, 5],
         [0, 0, 2, 5],
         [0, 4, 7, 5],
         [0, 8, 5, 5]], dtype=torch.int32),
 tensor([[0.2658, 0.9699, 0.2772],
         [0.0930, 0.7812, 0.0504],
         [0.6202, 0.8595, 0.2417],
         [0.6451, 0.5266, 0.3303],
         [0.1948, 0.2864, 0.6654]]))
```
Then I am passing it to the SparseTensor, and everything is completely fine,
```
data = ME.SparseTensor(features, coords=coordinates)
```
Returns `data` which is:
```
SparseTensor(
  Coords=tensor([[0, 3, 0, 7],
        [0, 1, 9, 5],
        [0, 0, 2, 5],
        [0, 4, 7, 5],
        [0, 8, 5, 5]], dtype=torch.int32)
  Feats=tensor([[0.2658, 0.9699, 0.2772],
        [0.0930, 0.7812, 0.0504],
        [0.6202, 0.8595, 0.2417],
        [0.6451, 0.5266, 0.3303],
        [0.1948, 0.2864, 0.6654]])
  coords_key=< CoordsKey, key: 15034981587763204738, tensor_stride: [1, 1, 1] in dimension: 3 >
  tensor_stride=[1, 1, 1]
  coords_man=< CoordsManager
	Number of Coordinate Maps: 1 
		Coordinate Map Key: 15034981587763204738, Size: 5
	Number of Kernel Maps: 0 >
)
```
But when I am trying to get the element with `batch_index=0` coordinates shuffled. It shouldn't be this way, right?
```
data.coordinates_at(0)
```
```
tensor([[8, 5, 5],
        [4, 7, 5],
        [3, 0, 7],
        [1, 9, 5],
        [0, 2, 5]], dtype=torch.int32)
```
Accessing through `data.coords[data.coords[:, 0] == 0][:, 1:]` gives result without shuffling:
```
tensor([[3, 0, 7],
         [1, 9, 5],
         [0, 2, 5],
         [4, 7, 5],
         [8, 5, 5]], dtype=torch.int32)
```

**Comment by chrischoy** [comment]
This is not a bug, although this might not be ideal.

Minkowski Engine (ME) uses a hash table internally to save the coordinates.

When you initialize a sparse tensor with coordinates, ME creates a coordinate manager along with a hash table for the coordinates.
So, it explicitly saves 1) the provided pytorch coordinates, 2) a hash table version of the same coordinates.

During feed forward, it does not create 1) pytorch coordinates, but creates 2) a hash table version of coordinates. So, all sparse tensors have associated hash table coordinates, but not pytorch coordinates.

Thus, `decomposed_coordinates_and_features`, `coordinates_at`, `features_at` and `coordinates_and_features_at` all compute coordinate index based on the generated hash table and the order in the hash table is more than often random.

**Comment by kumuji** [comment]
Oh, got it. Thank you for the explanation!
Should i add some line in the documentation, specifying this behavior?
