### ISSUE TITLE
Performance issues on Tesla V100

### ISSUE THREAD

**Issue by kumuji** [StanfordVL/MinkowskiEngine#121]
Hi! I was trying the example code on our university cluster which is using Tesla V100. And for some reason network (from examples/training.py) is 2-4 times slower than gtx1080 (not ti).

I changed the code a little:
```
        # Training
        net = net.cuda()
        net.train()
        for i, data in enumerate(train_iter):
            coords, feats, labels = data
            feats = feats.cuda()
            ts = time.time()
            out = net(ME.SparseTensor(feats.float(), coords))
            te = time.time()
            print(te-ts)

``` 
For both systems I have:
```
python 3.6.8
pytorch 1.4.0
gcc 7
cuda 10.1.243
cudnn 7.6
openblas
```
And the main difference is I have Ubuntu for 1080 and Cent7.7 for Tesla. Which I think is ok. 

On Tesla V100 I am getting(rounded seconds):
```
0.40
0.37
0.36
0.37
0.34
```
while on 1080 I got:
```
0.10
0.10
0.09
0.09
```
Looks very strange to me. And actually I have no idea where to look at.

**Comment by chrischoy** [comment]
How many CPUs do you have for each setup?

I suspect that OpenMP might have used too many threads for kernel map generation.

**Comment by kumuji** [comment]
@chrischoy , seems like it was the issue. 
When I set `OMP_NUM_THREAD` to 12 instead of default 96 it works way faster.
Thank you!
