### ISSUE TITLE
Some problems about MinkowskiChannelwiseConvolution

### ISSUE THREAD

**Issue by baifanxxx** [StanfordVL/MinkowskiEngine#125]
Hi , 
I am very interested in your MinkowskiChannelwiseConvolution. So, I used it in my net recently. However, it has some new problems which did not appear in my MinkowskiConvolution net before.

____________________________________________________________________
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    main()
  File "train.py", line 228, in main
    current_step=current_step, writer=writer)
  File "train.py", line 112, in train
    outputs = model(inputs)
  File "/home/baifan/anaconda3/envs/pt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baifan/anaconda3/envs/pt/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/baifan/anaconda3/envs/pt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baifan/graduation_project/pvcnn/models/shapenet/pvcnn.py", line 44, in forward
    features, _ = self.point_features[i]((features, coords))
  File "/home/baifan/anaconda3/envs/pt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baifan/graduation_project/pvcnn/modules/pvsconv_dws.py", line 44, in forward
    sparse_output1 = self.convB1(sparse_input)
  File "/home/baifan/anaconda3/envs/pt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baifan/anaconda3/envs/pt/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/baifan/anaconda3/envs/pt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baifan/anaconda3/envs/pt/lib/python3.7/site-packages/MinkowskiEngine-0.4.2-py3.7-linux-x86_64.egg/MinkowskiEngine/MinkowskiChannelwiseConvolution.py", line 177, in forward
    out_F[out_maps[k]] += input.F[in_maps[k]] * self.kernel[k]
IndexError: tensors used as indices must be long, byte or bool tensors
——————————————————————————————————————

It seems that the "sparse_input" has some ploblems, but if I use MinkowskiConvolution instead of MinkowskiChannelwiseConvolution, it works well. And the coords.dtype in "sparse_input" is torch.int32. I am very confused. On the other hand, I run the "sparse_tensor_basic.py" and replace the ME.MinkowskiConvolution with ME.MinkowskiChannelwiseConvolution, in this test, it works. But why it does not work in my net? Can you help me? If you need me to provide more information, please feel free to contact me.

Thank you!

**Comment by chrischoy** [comment]
Hmm, it is possible that the kernel map is malformed

Could you replace the line 177 of MinkowskiEngine/MinkowskiChannelwiseConvolution.py with

```
        for k in range(self.kernel_volume):
            try:
                out_F[out_maps[k]] += input.F[in_maps[k]] * self.kernel[k]
            except:
                print(self.kernel_volume)
                print("In Map k: ", in_maps[k])
                print("Out Map k: ", out_maps[k])
```

and let me know the results?
I suspect that in_maps[k] and out_maps[k] are None.

**Comment by baifanxxx** [comment]
Hi Chrischoy,
Thank you for your reply. I run it in your way. 

________________________________________
In Map k:  tensor([1281,  943,  969,  405,  239,   73,  251,  877,  493,  181,  396,  290,
         979,  953, 1214,   87, 1256,  233,   80,  535,  297,  964,  601,  675,
         226,  538, 1079,  504,  557, 1335,  449,  132,  605,  992, 1031, 1365,
         932,  337,  720,  476,  669, 1441,  681, 1049,  468,  426,  860,  702,
         140,  742,   25,  688,  111,  286, 1226, 1296,  163,  363,  299,  534,
          20,  420, 1344,  176,  939,  267,  944,   16,  645,  491,  406,  722,
           9,    7, 1192, 1419,  719, 1395,  319, 1301,  820,  477,  593, 1108,
         846,  970, 1008,  761,  114,  789,  651,  951,  804,  486,  195, 1227,
        1107,  732,  806,  466, 1318,  191, 1235, 1276,   57,  527,  306, 1181,
        1196,  825,  461, 1006,  375,  162,  352, 1358, 1234, 1396, 1366,  321,
         454,  522,   59,  121, 1151,  912,  161, 1185, 1431, 1409, 1265,  516,
         335,  588,  445,   95,  291, 1492,  219,  208,  344,  526,  158, 1251,
         929,  808,  993,  770,   14,  933,  554, 1386,  252,   15,  926,  376,
         578, 1182, 1279, 1461,  888,  566,  665,  183,  863,  674,  244,   28,
        1293,  108,  801, 1338, 1160,  656,  744,  137,  633,  520, 1147, 1255,
         105,  745,  587,  201,  624,  610, 1016,  440,  446, 1100, 1078,  571,
        1124,  122,  620,  467,  410,  945,  249,  747,  685, 1345, 1367,  525,
        1477, 1112,  757,  561,  680,  515,  899,   66,  896, 1349,  532, 1139,
         242, 1032, 1456,  204,  448,  115,  110,  400,  891,  906,  668,   70,
         886,   94, 1421, 1127,  671,  370,  356,  341,  134,  721,  421,  385,
        1199,  489, 1211, 1039, 1475,  170, 1184,  695, 1280,  676, 1002,  689,
         866,  602, 1172,  701,  786, 1330,  878,  459,  330, 1105,  549,  348,
           8,  673, 1402,  996,  550,  827,   17,  636, 1200, 1304,   90,  518,
         503,  227,  167,  925,   91,  890,  254, 1424,  407, 1382,  579,  310,
        1178, 1158, 1430,  210,  260, 1458,  788,  678, 1427,  887,   99,  844,
         355, 1014,  180,  123,  679, 1394,  113,  174,  575,  517,  292,  716,
         904, 1282, 1303,  275,  667,  106,  502,  379,  903,   86,  596,  408,
        1332,  186, 1117,  179,  273,  224, 1000, 1436,  823, 1254,  272,  799,
        1347, 1485, 1403,   21,  494, 1012,  519, 1154,  438,  762,  594,   24,
        1438,  302, 1232,  295,  499,  425,  643,  776,  384,  590,  798,  346,
        1442,  599, 1488,   29,  540,  143,  710,  245,  298,  803,  640, 1455,
        1055,  781,  452,  166,  573, 1242, 1299,  558,  443,   10,  816,   49,
         748,  855,  628,  852,  256,   27,  514, 1373,  559, 1144,  184, 1329,
         718, 1306, 1393, 1423,  458,   78, 1387,  340, 1348, 1482,  548,  424,
         373, 1270, 1287,  824,  699,  893, 1319,  433,  574,  902,  949, 1020,
        1311,   34,  709, 1315,  934, 1131,    3,  236,  910,  253,  482,  409,
        1171,  386,  693,  796,  663,  234, 1484, 1190, 1360, 1333,  694,  746,
        1385,  357,  543,  581,  156,  475,  474,  927,  968,  317, 1046,  358,
         311,  488, 1238,  439, 1376,  326,  544,  487, 1380, 1406, 1236, 1415,
         401, 1370,  805, 1169, 1230,  767, 1189, 1059, 1216, 1278,  395, 1425,
         595,  145,   23,  931,  159,  569,  259, 1468,  791,  331,   22,  985,
         995,  164, 1101,  983,  987,  815, 1038, 1342, 1093, 1283,  630, 1203,
        1072,  851,  442,  657,   37,  810,  857, 1453,  524,  404,  495,  537,
         141,   62,  473, 1246, 1339,  412,  147,  901,  130,  284,  541, 1156,
        1220,  119,  884,   63,  435,  144,  626,  967, 1005,  414,  666,  714,
         528,  418,  264, 1118,  608, 1028, 1361,  419,  428, 1058, 1269,  353,
         294,  641, 1274, 1439,  455,  305, 1489,  285, 1087,  849,  169,  413,
         607,  206,  737,  637,   11,  898,  262,  914,  617,  211,  359,  313,
          93, 1266,  172,   82,  634,  185,  870,  664, 1027, 1460,    5, 1001,
         659, 1264,   45, 1134,  362,  217,  760,  686,  104,  387,   26,  109,
         450,  220,  604,  690, 1490,  885, 1130,  177,  843, 1223,  935, 1245,
         736, 1413,  282,   12,  947, 1472,  366,  859,  883,  427,  478,  576,
         235, 1065, 1294,  692,  639,  734,  856,   83,   31,  280,  560, 1188,
         652,   89,  564,   98,  743,  390,  954,  190,  255,  257,  683,  209,
         334, 1023,  194, 1071,  838,  453,  196,  661, 1346,  303,  247,   69,
        1305, 1372,    6,  155, 1466,  730,  705,  632,  327,   46,  655,  149,
         586,  728, 1437, 1061,  268,   44,   71,  135, 1163,  918, 1381, 1416,
          96,   50, 1029,  501,  644,  774,  882,  148,  202,  398, 1352,  919,
         822, 1388,  178, 1454, 1148,  471,  530,  287,  812,  785, 1176,  432,
        1126, 1140,  508, 1272, 1357,   48,   85,  243,  818,  222,  168,  388,
         850,  182,  950,  315, 1081,  229,  116, 1356,  325,  231, 1066,  647,
         531,  232,    0,  372,  269, 1351,  895,  741,  361, 1291, 1183, 1314,
           4,  787, 1070,  684,  913, 1487,  271, 1247, 1307, 1011, 1354,   97,
        1285,  188, 1297, 1003,  307,  552,   92,  795,  129, 1187,  971, 1233,
         703,  316,   61,  417,  490,  623,  609,  481,  301,  874, 1015,  258,
         654,   88,  484,  465, 1412, 1103,  802,  218, 1369,  354,  314,  892,
         706,  510,  916, 1141, 1152,  713,  911, 1260,  469,  726,   35,  584,
         807,  444,  320,  546,  858,  653,  173,  862, 1033,  228, 1389,  592,
         567,  759, 1399,  328,  463,  523, 1271, 1088,   40,  464,  349, 1273,
         456,  241,  128, 1465, 1474,  127,  811,  402,  937,  120,  512, 1080,
        1153,  293,   58,  374,  240,  479, 1275,  221,  154,  441, 1207, 1418,
         322,  603,  381, 1384, 1258,  225,  783, 1167,   52, 1114,  613, 1462,
         200, 1109,  308,  248,  192, 1374,  649,  133, 1483,  153,  782,  638,
          13,  829, 1292,  391, 1062,  351,  378,  957,  940,   81, 1037, 1106,
        1073, 1170,  112, 1175,  958, 1018,  946,  462, 1201, 1231,  118,   53,
         336,  187,  837,  205,  570,  772, 1004,   84,  265,   47,  606,  568,
        1263,  199, 1480,  826,  215,  872,  101, 1267,  393,  682, 1493, 1125,
        1239,  875,  505,   19,  662,  725,  369,  542,  973,  715,  591,  345,
          64,  551,  711,  483, 1021,  511, 1091, 1076,   51,  687,  497],
       device='cuda:0', dtype=torch.int32)
Out Map k:  tensor([ 852, 1065,  769,  179,  548,  585,  472, 1056,  601,  351,  402,  308,
        1269, 1365,  879,  595, 1211,  680,  717,  439,  363, 1374,  517,  271,
         559,  661,  737,  602,  515,  789,   70,  640,   56,  971, 1311,  958,
         992,  645,  384,  474,  603, 1161,   35,  828,  116,  247, 1185,  609,
         174,  991,  636,   54,  539,   47, 1199, 1425,   21,  175,  635,    1,
         656,  307, 1003,  297,  853,  126,  744,  103,  697,  161,  454,  492,
         534,  459, 1035,  856,  331,  767,    3, 1388,  935,  720,  313, 1047,
         930, 1041, 1270,  788,  256,  918,  311,  809, 1175,  386,  178, 1261,
         994,  824, 1352,  576, 1276,  468, 1314,  898,  226,  658,  269, 1343,
        1241, 1170,  571,  955,  420,  389,   34,  876, 1231, 1285, 1390,   40,
         388,  537,  513,   99, 1124, 1431,  132, 1153, 1371, 1210,  896,  518,
         398,  231,  475,  239,  425, 1061,  167,  660,  466,  652,  261, 1004,
         899, 1243,  755, 1395,  707, 1000,  177, 1015,   10,  488,  747,  206,
         379, 1156,  968, 1130, 1069,  443,  369,  207, 1255,  336,  413,   88,
         869,  214,  953, 1239, 1467,  195, 1411,  286,  615,  196, 1181,  818,
         211, 1117,  134,  647,  525,  620, 1347,  400,  586,  791,  986,  335,
        1332,  185,  193,  232,  245, 1014,  456, 1477,  533, 1481, 1256,   31,
        1154, 1387,  914,   29,  703,   75, 1046,  135, 1013,  912,  314, 1019,
         479,  957, 1344,  170,  558,  166,  277,  689, 1039,  844,  692,  133,
        1214,  324,  882,  893,  704,  611,  501,  650,  220,   30,  119,  188,
        1172,  374, 1059, 1113, 1225,  394,  846,  579,  980,  700, 1240,  330,
        1137,  215, 1067,   63,  825, 1290,  785,  237,  486, 1126,   85,  354,
          61,  526,  890,  946,   43, 1182,  182,  433,  913, 1259,  511,  218,
          94,  447,  210, 1416,  341, 1189,  709, 1247,  405, 1456,  535,  445,
        1253, 1125, 1482,  623,   66, 1109,  834,  446, 1009,  777,   83, 1486,
         244, 1029,    4,  276,  371,  949,  643,  143,  416,  591,  600,  360,
        1131,  964, 1437,  442,  359,    6,   25,  678, 1278,  529,  316,  596,
         734,  719,  904,  438,  471,   53, 1068,  920,  851, 1413,  349,  786,
         989, 1055, 1451,   91,  184, 1283,  242, 1393,  705, 1315,  437,  264,
        1414,  157,  965,   64,  641,  118,  566,  837,  233,   97, 1118,  679,
        1072,  131, 1329,  290,  283,  262,  169,  687,  543,  865,   87,  927,
        1280, 1392,  477,  296,  613, 1183, 1293,   95,  502,   86,  916,   90,
        1326, 1367,  265, 1074,  362,  144,  505, 1492,  115, 1058,  554, 1195,
         150,  862, 1258,  830,  664,  683, 1092,   68, 1232, 1460,  381,  375,
         648, 1053, 1057,  889,  499, 1335, 1406,  587,   60,  775, 1070, 1446,
        1188,  299,   45,  738, 1048,  919,  588,  253,  780,  140,  713,  278,
        1106,  550,  455, 1063,  100,  252, 1095,  884,  840, 1218,  202, 1223,
         815,  305,  162,  217,  489,  458,  597, 1318, 1052,  293, 1127,  657,
         465,  345, 1104,  199, 1026,  101,  668,  421, 1102,  838,  826, 1077,
         383, 1110, 1144, 1251, 1322, 1389, 1021, 1494,  984, 1377,  393, 1082,
         691,  522,   51, 1155,  448,  663,  327,  979, 1002,  281,  173, 1443,
        1215,  509,  845, 1030, 1005, 1331, 1176, 1167,  849,  820,  378, 1049,
        1453,  770,  452,  406,  302, 1025, 1272,  974,  694,  159,  649,  292,
          44,  408,  321, 1302, 1368,  711,  428,  772,  546,  461,  151,  757,
         891,  155, 1150,  235,  190,  303,  222, 1081, 1487,  514,  430,  160,
         320,  318,  148, 1386,   13,  939,  836,  621,  198, 1233, 1421,   52,
         552,  104,  950, 1090,  581,  577, 1436,  246,  883, 1418,  114,  572,
         187,  260, 1152,  481,  254,  796,  714, 1141,  243,  527,  432,  257,
         578, 1257,  201,  372,  549,  427, 1267,  315,  886, 1364,   82, 1228,
          22,  776,  163,  859,  138,   19, 1299,  259,  183,  106,  653,  464,
         340,  460,   59,  524, 1190, 1016,  739,  141, 1355, 1180, 1062, 1097,
        1493, 1037,  564,  614, 1360,  934,   79, 1107, 1444,  228,  219,  145,
          71, 1366,  724,  272,   76, 1193,  960,  434,  107,    8,  356, 1254,
         391,  328,   27,  180, 1396,  395, 1454,  426,   62,  662,  204,  626,
         482, 1200,  419, 1045, 1087,   92,  476,  693, 1008,  192,  690,  441,
        1403,  729,    0,  673, 1305, 1490,  137,  628,  410,  494,  212,  453,
          58,  987,  976, 1274,  491,  540,  227,  309, 1298, 1349, 1472, 1120,
         291,    7,  827,  205,  368, 1100, 1105,  521,  542,  516,  870, 1301,
         895, 1264,  467,  795,  805,  528,  637,  722, 1351,  823,  880,  688,
        1103,  790,  473,  807, 1169,  113,   80,  117, 1184,  444,  684,  122,
         937,  710, 1282,  267, 1372,  123,  361, 1334,  319,  651, 1166,   77,
         599,  285,  208,  715,  200, 1245, 1160,  750,  172, 1308, 1333,  868,
         557,  774, 1027,   69, 1319, 1207,   49, 1294,  801, 1310,  874,  270,
         923,  702,  797, 1011,  681,  568,  414, 1464,  604, 1408, 1296, 1044,
         463,  580,  485,  532,  565,  629,  191,    9,  608, 1007,  855,  112,
         306,  712,   18,  531, 1040, 1442, 1381,  594,  967,  109,  209, 1116,
         250,   32,  732,  725, 1083,   46, 1327, 1133,   50, 1173,  332,  676,
         988,  545,  255,  357, 1461,  153,  561,  864,  799,  279, 1379,  343,
         407,  877,  731,   73,  127,  348, 1148,  850,   28,   37,  560, 1171,
         605,  618,  312, 1491,  773,  490, 1093,   15,  783,  365,  493,  752,
         982,  706,  333,   81,  631,  136, 1303,  128,  718,  497, 1284, 1402,
         154,  696,  530, 1291, 1447,  638, 1229, 1204,   17, 1206,  487,  736,
         322,  746,   89,  418,  364, 1128,  409,  412, 1450,   55,  806,  334,
          23,  903, 1249,  287, 1028,  224,   98,  932,  871,  234,  816,  995,
        1177, 1226,  385,  808, 1174,  998,  924,  701, 1478, 1112,  353,  376,
         606,  344,  787,  669,  294,  973, 1307,  616,   24,  541,  519,  632,
        1010,  298, 1234, 1033,  666, 1252,  593, 1338,  667,  158, 1079, 1266,
         829,  742,  105,  639,  671,  940,  598,  194,  885,  337,  644,  520,
         483,  176,  248,  429, 1316,  506, 1246, 1321,  590,  295,  424],
       device='cuda:0', dtype=torch.int32)
27
In Map k:  tensor([910, 112, 212,  ..., 167, 200, 560], device='cuda:0',
       dtype=torch.int32)
Out Map k:  tensor([852, 417, 179,  ..., 590, 295, 424], device='cuda:0',
       dtype=torch.int32)

**Comment by chrischoy** [comment]
Thanks for reporting the error. Please pull from the git repo and install again.

**Comment by baifanxxx** [comment]
Thank you for your warm help, I will continue to follow your work.

**Comment by Labo9527** [comment]
Sorry to bother you. I am confused about whether MinkowskiChannelwiseConvolution is actually MinkowskiDepthwiseConvolution. If you have any ideas, please tell me. Thank you.
