### ISSUE TITLE
API Notation Problem

### ISSUE THREAD

**Issue by SwagJ** [StanfordVL/MinkowskiEngine#126]
Hi, 

When I tried to use the dense attribute of class SparseTensor.
https://stanfordvl.github.io/MinkowskiEngine/sparse_tensor.html
I think the notation about dimension is wrong? I created a batced coord tensor with the following value:
tensor([[ 1., 66., 58., 63.],
        [ 1., 10., 39., 33.],
        [ 1., 64., 96., 58.],
        [ 1., 80., 34., 91.],
        [ 1., 96., 62., 98.],
        [ 1., 16., 30., 57.],
        [ 1., 66., 92., 96.],
        [ 1., 13.,  6., 59.],
        [ 1., 47., 23., 36.],
        [ 1., 15., 30., 21.]])
And feature of all ones with size(10,1)
After used dense() on the sparseTensor created. 
I got dimension like this:
torch.Size([2, 1, 87, 91, 78]),
which makes for sense to me as (batch dim, feature_dim, spatial_dim) instead of (batch dim, spatial_dim, feature_dim) marked in the API. 

Also, I have an additional question. For MinkowskiConvolution, is that possible to get different coordinates from input as output? For example apply an offset along one dimension of coordinate? 
Thank you very much!

**Comment by chrischoy** [comment]
Got it thanks for catching this.

You can use arbitrary coordinates for both input and output.
Please refer to https://github.com/StanfordVL/MinkowskiEngine/blob/master/tests/conv_on_coords.py#L78 for details.

**Comment by SwagJ** [comment]
Thanks a lot!
