### ISSUE TITLE
[bug] batch norm error with multi gpu training 

### ISSUE THREAD

**Issue by jbjeong** [StanfordVL/MinkowskiEngine#129]
Hello, thank you for great code.

I found a bug in multi gpu training.
In multi gpu training, 
```python
net = ME.MinkowskiSyncBatchNorm.convert_sync_batchnorm(net)
```
then the batch norm is replaced with MinkowskiSyncBatchNorm.
When the model forwarded, the following error occurs. 
Message: "RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input."

![GetImage](https://user-images.githubusercontent.com/30853761/80091307-d5b42700-859b-11ea-9c04-a28bbfa4f0d5.png)

But, I found that when I fix this line by removing squeeze and unsqueeze,
The error does not occur. 

https://github.com/StanfordVL/MinkowskiEngine/blob/93b79781862206ef771376195ae6443fcfe9b4ce/MinkowskiEngine/MinkowskiNormalization.py#L92

```python
output = self.bn(input.F.unsqueeze(2)).squeeze(2)
# ->
output = self.bn(input.F)
```
Why do 'unsqueeze' and 'squeeze' is needed?

**Comment by chrischoy** [comment]
Thanks for reporting this error,

This was due to a weird requirement in old pytorch versions. I put a comment on the line

```
# Weird requirement for the input to have > 2 dimensions which is unnecessary.
```

It seems that they updated the code. I'll push a fix for this.

**Comment by jbjeong** [comment]
Thanks!
