### ISSUE TITLE
[docs]  demo/images/demo_reconstruction.png  NOT exists

### ISSUE THREAD

**Issue by ElectronicElephant** [StanfordVL/MinkowskiEngine#131]
Just a minor issue. 

In `https://stanfordvl.github.io/MinkowskiEngine/demo/sparse_tensor_reconstruction.html`, the image at the bottom of the page doesn't exist.

**Comment by chrischoy** [comment]
Got it thanks for letting me know. I'll update the doc.

**Comment by chrischoy** [comment]
Added to the doc.
