### ISSUE TITLE
understand coord_key and coord_manager

### ISSUE THREAD

**Issue by hua-wu-que** [StanfordVL/MinkowskiEngine#145]
Hi!

I am having some difficulty understanding the mechanism of coord_key and coord_manager. Can you point me to some reference or tutorial since I didn't find any. Thank you!

**Comment by chrischoy** [comment]
Unfortunately, I don't have a tutorial or documentation on that. I need to write one.
But to summarize,

First, I'll define *a set of coordinates* as a `C` matrix associated with a sparse tensor.

Each sparse tensor has a set of coordinates (`C` matrix). For example, everytime we apply a strided convolution/pooling (stride > 1), we create a new set of coordinates. However, all intermediate convolution/pooling with stride=1 use the existing coordinates.

These unique sets of coordinates have a unique `uint64_t` key assigned to them. We call these, `coords_key`. Thus, multiple sparse tensors can share the same coordinates by simply referring to the key.

A coordinate manager contains multiple coordinates and handles operations that require multiple set of coordinates. For example, to generate a kernel map, you need to know the input and output coordinates. These operations are handled by the coordinate manager and it can also create a new set of coordinates.
