### ISSUE TITLE
Memory Leak on MinkowskiConvolution

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [StanfordVL/MinkowskiEngine#150]
Hi, thank you for the great work. I recently updated to the latest version and I am now observing a gradual increase in GPU memory consumption when using the MinkowskiConvolution operation, until the system eventually crashes due to lack of memory. 
I remember running the same network without this issue a few months ago, do you know what could be the cause?

**Comment by chrischoy** [comment]
Thanks for reporting the issue.

I found a potential problem and uploaded the fix on the branch https://github.com/StanfordVL/MinkowskiEngine/tree/issue150.

Could you try to install the branch by

```
git clone https://github.com/StanfordVL/MinkowskiEngine.git
cd MinkowskiEngine
git checkout issue150
export CXX=g++; python setup.py install
```

**Comment by chrischoy** [comment]
Another option is setting the memory manager backend to raw CUDA calls.

https://stanfordvl.github.io/MinkowskiEngine/coords.html#MinkowskiEngine.MinkowskiCoords.set_memory_manager_backend

Put this code when you first import the engine.

```python
>>> import MinkowskiEngine as ME
>>> # Set the GPU memory manager backend to raw CUDA calls
>>> ME.set_memory_manager_backend(ME.MemoryManagerBackend.CUDA)
```

**Comment by chrischoy** [comment]
Another way to check whether it is memory leakage in the engine is to call

`torch.cuda.empty_cache()` every iteration after backward.

I recently trained a network with a latest version with the pytorch backend and had no leakage, but I'm not sure what's causing the problem in this issue.

**Comment by VitorGuizilini-TRI** [comment]
Thanks for the quick reply, I will try these solutions as soon as possible.

**Comment by VitorGuizilini-TRI** [comment]
Using `torch.cuda.empty_cache()` had no effect on the memory leak. However, if I remove the MinkowskiConvolution from the computational graph the leak disappears. 

I am getting the following when trying to set up the memory manager backend (0.4.2 version):
```
AttributeError: module 'MinkowskiEngine' has no attribute 'set_memory_manager_backend'
```

**Comment by chrischoy** [comment]
It seems like the engine is not up-to-date.

Could you install from the latest source?

```
pip3 install -U -I git+https://github.com/StanfordVL/MinkowskiEngine
```

**Comment by VitorGuizilini-TRI** [comment]
I am having issues transitioning to Pytorch 1.5 in order to use the latest source, so for now it will have to be Pytorch 1.4, is that doable? Can you point me to a compatible older release?
Sorry for all these questions, I am trying to revive an old project that uses this engine, but apparently things have changed a lot in the past few months. :)

**Comment by chrischoy** [comment]
https://github.com/StanfordVL/MinkowskiEngine/tree/mink-0.4.2-pytorch-1.4

I removed pytorch 1.5 dependencies.

**Comment by VitorGuizilini-TRI** [comment]
It seems to be working, thank you very much! I will debug further to understand what happened once I have some time, but it should be enough for now.

**Comment by chrischoy** [comment]
Okay, closing the issue.

**Comment by chrischoy** [comment]
I get some questions regarding this.

There's no memory leakage in 0.4 and 0.5. The reason that GPU runs out of memory is because of the pytorch cache allocation.

Basically, pytorch reserves memory once it uses GPU memory for later faster memory allocation. Unlike 2D convnets, 3D point clouds have different number of points, which forces the pytoch to reserve a new large memory space everytime a point cloud size is larger than the current fragmented memory size.

To resolve this, you have to force pytorch to clear the cache by `torch.cuda.empty_cache()` and force pytorch to release memory space reserved and are too fragmented to reserve a new memory space.

**Comment by huassaue** [comment]
> 再次强调，我已经使用它很长时间了，进行了 10 万次甚至更多的迭代，没有发现任何内存泄漏。所有用户也是如此。如果您遇到问题，请提交可重现代码的问题，因为我无法重现您的错误，而且我不认为这是由 Minkowski 引擎引起的。

hello, I used I used it, but it's still invalid, but it's still invalid.

code is:
    for epoch in range(num_epochs):
        
        net.train()
        train_loss = 0.0
        train_iter = iter(train_loader)
        for j, data in enumerate(train_iter):
            last_net_output = None  
            batch_last_T_w_b = None  
            
            for k, (
                # batch_raw_point_cloud,
                # batch_hist_meas_coords,
                # batch_hist_meas_feats,
                batch_cur_meas_coords,
                batch_cur_meas_feats,  
                batch_cur_gt_coords,
                batch_cur_gt_feats,
                batch_cur_T_w_b,
            ) in enumerate(data):

                batch_net_input_coords, batch_net_input_feats = update_net_input(
                    last_net_output,
                    batch_cur_T_w_b,
                    batch_last_T_w_b,
                    batch_cur_meas_coords,
                    batch_cur_meas_feats,
                    voxel_size,
                    range_length,
                    device,
                )

                inp = ME.SparseTensor(
                    batch_net_input_feats, batch_net_input_coords, device=device
                )

                cm = inp.coordinate_manager
               
                target_key, _ = cm.insert_and_map(
                    batch_cur_gt_coords.to(device),
                    # force_creation=True,
                    # allow_duplicate_coords=True
                    string_id="target",
                )

                outp, decoder_cls, targets = net(inp, target_key)

                num_layers, loss = len(decoder_cls), 0
                for decoder_cl, target in zip(decoder_cls, targets):
                    curr_loss = criterion2(
                        decoder_cl.F.squeeze(),
                        target.type(decoder_cl.F.dtype).to(device),
                    )
                    loss += curr_loss / num_layers

             
                gt = ME.SparseTensor(
                    batch_cur_gt_feats, batch_cur_gt_coords, device=device
                )
                label = gt.features_at_coordinates(outp.C.to(torch.float32))

                loss += criterion1(label, outp.F)

                # print(
                #     f"Epoch {epoch}/{num_epochs} \t Iteration {j}\t Step {k}\t Loss: {loss.item():.3e}"
                # )

                # Backpropagation
                loss.backward()
                optimizer.step()
                optimizer.zero_grad()

                
                del inp
                del gt
                torch.cuda.empty_cache()
