### ISSUE TITLE
behavior of tensor_stride

### ISSUE THREAD

**Issue by hua-wu-que** [StanfordVL/MinkowskiEngine#152]
Hi Choy,
There seems to be a difference about the kernel_size compared to standard comvolution. Is the receptive field not kernel_size but tensor_stride*kernel_size? (in 3d case, each neural sees a coordinate block of size (tensor_stride*kernel_size)**3)

**Comment by chrischoy** [comment]
Its the same kernel size you use in regular convnets. In each layer, a neuron sees kernel size number of neurons below for each axis. When you explicitly compute the coordinates, it becomes kernel size times the tensor strie.

**Comment by hua-wu-que** [comment]
What is the relation between the "tensor stride" and "coords value"? 

I can understand the case if the coords=[0,128,256] and tensor_stride=128, in such case the tensor_stride indicate the gap between two consecutive coords

 but what if I initialize a SparseTensor(for simplicity assume 1D in this case) with coords=[0, 1, 2] (omit batch index) and stride=128, does it make sense in this case?
