### ISSUE TITLE
Question About Recover Intermediate Conv Layer output coords back to original

### ISSUE THREAD

**Issue by SwagJ** [StanfordVL/MinkowskiEngine#155]
Hi, 

Let's say I have a coord list, named A, of Nx3 at input. Then I fed it into 3 layers of  SparseConv with stride of 2. Its output named B is of size Mx3. Is there a attribute that helps me map B's coord list back to  A's, i.e. transform output B's coord list back to original input spatial size.

**Comment by chrischoy** [comment]
If you use transposed pooling, https://stanfordvl.github.io/MinkowskiEngine/pooling.html#minkowskipoolingtranspose, with stride size 8, 2* 2 * 2, you will be able to copy the features inside a stide 8 voxel to all stride 1 voxels.
