### ISSUE TITLE
any plan for supporting CMakeList.txt?

### ISSUE THREAD

**Issue by rancheng** [StanfordVL/MinkowskiEngine#159]
I'm working with configuring this project on CLion to debug some Cuda code I wrote recently, and am curious about any future plan of support of CMake?

**Comment by rancheng** [comment]
close since I have translated a CMakeList.txt from the makefile. I will reopen if anyone needs it.

**Comment by chrischoy** [comment]
@rancheng 
Do you think CMakeList would be better to integrate with other projects? I'm open to change the Makefile to CMakeList?

**Comment by rancheng** [comment]
I think so, at least I can debug the C++ code with CLion and other tools smoothly, I have a very ugly CMake debug version of Minkowski Engine 0.4.3.

In case anyone has similar requirement to debug and develop this library, here's the library with `CMakeLists.txt` support: [mink-cmake](https://github.com/rancheng/Minkowski-Engine/tree/cmake)

A detailed debug tutorial is in the front section of README.md in this `cmake` branch.
