### ISSUE TITLE
multi-gpu training got OOM

### ISSUE THREAD

**Issue by chenkl1995** [StanfordVL/MinkowskiEngine#16]
i can use batch_size=8 when training in single-gpu but got OOM when trainging with 4 gpus with batch_size=1, the multi-gpu trainging code is just follow the `examples/multigpu.py`, i am not sure what the problem lying, could you give me some suggestions about it?

**Comment by chrischoy** [comment]
Thanks for reporting the issue. Are you using the latest commit?

**Comment by chenkl1995** [comment]
> Thanks for reporting the issue. Are you using the latest commit?

Sure.I try both 0.2.4 and 0.2.5 and both got this situation.

**Comment by chrischoy** [comment]
I see. I'll look into this.

Btw, did you use `with torch.cuda.device(...)` like https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/multigpu.py#L97?

For 0.2.5, the sparse tensor initialization requires such gpu context.

**Comment by chenkl1995** [comment]
> I see. I'll look into this.
> 
> Btw, did you use `with torch.cuda.device(...)` like https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/multigpu.py#L97?
> 
> For 0.2.5, the sparse tensor initialization requires such gpu context.

Thanks!
Sure, I notice this change which is different 0.2.4 and add this line when I using 0.2.5

**Comment by zxczrx123** [comment]
> > I see. I'll look into this.
> > Btw, did you use `with torch.cuda.device(...)` like https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/multigpu.py#L97?
> > For 0.2.5, the sparse tensor initialization requires such gpu context.
> 
> Thanks!
> Sure, I notice this change which is different 0.2.4 and add this line when I using 0.2.5

I had the same problem, but the above method didn't work.Have you solved it now?

**Comment by zxczrx123** [comment]
@chenkl1995 I had the same problem, but the above method didn't work.Have you solved it now?
