### ISSUE TITLE
About ILP(instruction-level parallel) on matmul in convolution.cu

### ISSUE THREAD

**Issue by xmyqsh** [StanfordVL/MinkowskiEngine#162]
Can `matmul` in `convolution.cu` be further accelerated by ILP(instruction-level parallel)?

**Comment by chrischoy** [comment]
Please elaborate

**Comment by xmyqsh** [comment]
Use more register with fewer threads, but more parallel independent instruction in a thread.
Fewer threads allow fewer shared memory access but more local register access.

Reference:
https://www.nvidia.com/content/GTC-2010/pdfs/2238_GTC2010.pdf

**Comment by chrischoy** [comment]
Please elaborate on the implementation level

**Comment by xmyqsh** [comment]
demo of ILP(instruction level of parallel) on matmul in convolution.cu
https://github.com/StanfordVL/MinkowskiEngine/pull/163
I use `NumILP` times shared memory to achieve instruction-level parallel.
This is just a demo, `NumILP` can be further tuned by using another for loop.

**Comment by xmyqsh** [comment]
hide memory copy and computation latency as well as fewer threads using by ILP(instruction-level parallel)
https://github.com/StanfordVL/MinkowskiEngine/pull/164
