### ISSUE TITLE
Are the coordinates (i.e geometric information) automatically used as features?

### ISSUE THREAD

**Issue by MacOS** [StanfordVL/MinkowskiEngine#17]
Thank you for your work and making it public!

My question relates to the SparseTensor. In the provided example you wrote

`
sinput = ME.SparseTensor(features - 0.5, coords=coordinates).to(device)
`

where features are the colors, i.e. Red, Green, and Blue. Am I correct when I say that this does not take the coordinates into account as features? In other words, If I want to include the geometric information I have to include them as features? I'm asking because you seem not to normalize the coordinates.

Thank you in advance!

**Comment by chrischoy** [comment]
It does not add coordinates into the feature vector. It would be best to think of it as an extension of a 2D dense tensor. In dense 2D or images, pixels are located at specified coordinates with color values.
You could represent the same image as a sparse tensor and it would be the exactly the same, bur less efficient. So, we do not add coordinates as a feature. Coordinates are used for defining the neighborhood for convolutions only.

**Comment by MacOS** [comment]
Thank you very much for the fast response!
