### ISSUE TITLE
Neither CPU nor GPU usage at 100%

### ISSUE THREAD

**Issue by maxjaritz** [StanfordVL/MinkowskiEngine#18]
Hello,
Thanks for your great implementation. I wanted to know what the bottleneck is in the training. In my example the MinkowskiEngine uses the 20 cores of my CPU, but the usage is always pretty low. Also the GPU is not at 100%.

I wonder if it would make sense to use multiple workers in the dataloader. Right now I get an error when activating multiprocessing in the dataloader with num_workers > 0, because SparseTensor already uses multiprocessing. To fix this, would it be possible to split the CPU cores differently? For instance, one could use 2 workers and each worker uses 10 cores to construct the SparseTensor.

Do you think a speedup would be possible like this? I found that the number of threads is hidden in the CoordsManager, but maybe it could be made available in the SparseTensor arguments.

Thanks

**Comment by chrischoy** [comment]
Hi, I've updated the CPU code and the GPU code. Could you try the latest version of the Minkowski Engine?

Also, it is always a good idea to use multiple workers for data loading.

Currently, it is difficult to control how the hyper threads would split the jobs, so it is best to vary the number of threads to maximize the utilization experimentally.

To control the number of threads, use

```
export OMP_NUM_THREADS=5; python main.py --arg 1 --arg 2 ..
```

**Comment by chrischoy** [comment]
Closing it for no updates.

**Comment by MaxShi007** [comment]
> 



> I'm facing issues when trying to use multiple workers for data loaders. Whenever I set `num_workers>0` on my dataloader I get the following error:
> 
> `TypeError: cannot pickle 'MinkowskiEngineBackend._C.CoordinateMapKey' object`
> 
> Is it possible to use num_workers>1 with Minkowski Engine?

I have same question, Have you solved this problem？

**Comment by thiagodma** [comment]
I didn't manage to solve this problem @MaxShi007

**Comment by nuneslu** [comment]
Hi, any updates in this? I have been trying to use `pytorch.multiprocessing` but also the Minkowski layers cannot be pickled and throws the same error
