### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by aniqueakhtar** [StanfordVL/MinkowskiEngine#19]
I followed these commands to create and install the necessary requirements for the MinkowskiNet:
`conda create -n py3-mink python=3.7 anaconda
conda activate py3-mink
conda install openblas numpy
conda install -c bioconda google-sparsehash
conda install pytorch torchvision -c pytorch `

Then I follow these to compile the program:
`conda activate py3-mink
git clone https://github.com/StanfordVL/MinkowskiEngine.git
cd MinkowskiEngine
python setup.py install`

The first error I face is in this line while installing `openbias`:
`conda install openblas numpy`
<img width="663" alt="Screen Shot 2019-07-29 at 5 05 42 PM" src="https://user-images.githubusercontent.com/2750083/62091388-7e0fa780-b225-11e9-9efc-69a1c0ccbf53.png">

I can get around this error by installing openbias through: `conda install -c anaconda openblas `

However once I run this command: `python setup.py install`
I get the following error:

<img width="1241" alt="Screen Shot 2019-07-29 at 5 20 32 PM" src="https://user-images.githubusercontent.com/2750083/62091403-9c75a300-b225-11e9-8d39-2a4080afd4c6.png">

I am not sure how to resolve this. Any help would be greatly appreciated. 

Thanks

**Comment by pxiangwu** [comment]
Hi, you need to use cuda=10.0

**Comment by aniqueakhtar** [comment]
I see that makes sense.
There's a lot of programs that use my current installation of CUDA. Is there any way I can upgrade the cuda without effecting the older installations? Like maybe running a docker image or something along those lines with the updated cuda?

**Comment by pxiangwu** [comment]
You can use modules to manage different environment: http://modules.sourceforge.net/
With modules, you can easily switch to different cuda versions.
