### ISSUE TITLE
Importing Open3D before torch leads to core dump in examples/indoor.py

### ISSUE THREAD

**Issue by lyp0413** [StanfordVL/MinkowskiEngine#2]
https://pastebin.com/bKJYeFgT

**Comment by chrischoy** [comment]
Can you put more info when this happens?
It seems like open3d had some problems.

Can you run other examples other than the `indoor.py` without a problem?

**Comment by lyp0413** [comment]
I solved the problem by importing open3d before torch.
But I still want to know why it happened.

**Comment by chrischoy** [comment]
In `examples/indoor.py:L6`, 
https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/indoor.py#L6, `open3d` is already loaded before torch.

What exactly do you mean by `importing open3d before torch`?

**Comment by lyp0413** [comment]
@chrischoy
I replaced #L5-L9 just with "import open3d as o3d" and loaded it after torch.

**Comment by chrischoy** [comment]
I cannot reproduce this issue on my ubuntu 16.04 and 18.04.

However, it seems like it is similar to https://github.com/pytorch/pytorch/issues/6194

**Comment by lyp0413** [comment]
thanks a lot


 
---Original---

**Comment by chrischoy** [comment]
Found similar issue on the Open3D issue page https://github.com/intel-isl/Open3D/issues/922
They imported open3d first like the examples/indoor.py. However, as this is an issue in open3d and pytorch, Ill leave this issue closed until they come up with a solution.
