### ISSUE TITLE
Using PyTorchs DataSet, DataLoader, and increasing the Batch Size.

### ISSUE THREAD

**Issue by MacOS** [StanfordVL/MinkowskiEngine#21]
Thank you for your work! In particular, for open sourcing the source code!

My question is: How can I use PyTorch DataSet and DataLoader class to increase the Batch Size? (If it is possible at all)

As far as I understand, I simply have to append the mini batch index to the coordinates matrix [according to this](https://stanfordvl.github.io/MinkowskiEngine/generalized_sparse_conv.html). In your example code, you show how this is done using a function ```data_loader``` [common.py](https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/common.py). However, I wonder if this is also possible the standard PyTorch way by defining a DataSet class that inherits from PyTorchs DataSet class and using their DataLoader.

Thank you in advance!

**Comment by chrischoy** [comment]
Sorry for the late reply.

Yes, you can with batch size > 1.

I uploaded the example training with a dataset that inherits pytorch `Dataset` and with pytorch `DataLoader`.

Please check out https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/two_dim_training.py

**Comment by GaoQiyu** [comment]
pytorch dataloader need same input number for each sparse tensor in one batch
how to solve this , or just random choice a fix number of point?
but point number in different scene is different .

**Comment by GaoQiyu** [comment]
> Sorry for the late reply.
> 
> Yes, you can with batch size > 1.
> 
> I uploaded the example training with a dataset that inherits pytorch `Dataset` and with pytorch `DataLoader`.
> 
> Please check out https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/two_dim_training.py

pytorch dataloader need same input number for each sparse tensor in one batch
how to solve this , or just random choice a fix number of point?
but point number in different scene is different .

**Comment by chrischoy** [comment]
Please refer to https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/modelnet40.py

Basically, you need a custom collation function.
