### ISSUE TITLE
Can you provide a pre-trained model on S3DIS dataset?

### ISSUE THREAD

**Issue by lyp0413** [StanfordVL/MinkowskiEngine#25]
Can you provide a pre-trained model on S3DIS dataset?Thank you.

**Comment by aniqueakhtar** [comment]
And preferably some code on how the training was done. Thank you

**Comment by chrischoy** [comment]
Hi, the code is posted here https://github.com/chrischoy/SpatioTemporalSegmentation/

I'll add the stanford data preprocessing and training as well.

**Comment by chrischoy** [comment]
Closing the issue. Weights available on the repo
