### ISSUE TITLE
how to train in batch

### ISSUE THREAD

**Issue by liaocs2008** [StanfordVL/MinkowskiEngine#26]
Each input may have different sparsity, so COO representation may have different number of coordinates. How to concatenate them into batches? Shall I allocate the same space for each input? 

Thanks for your attention!

**Comment by chrischoy** [comment]
Hmm, it looks like you haven't read the paper https://arxiv.org/abs/1904.08755.
Please read it as well as the training example https://stanfordvl.github.io/MinkowskiEngine/
