### ISSUE TITLE
Using multiple features for one coordinate

### ISSUE THREAD

**Issue by lyp0413** [StanfordVL/MinkowskiEngine#3]
I found that ME provided ME.utils.sparse_quantize() to downsample a dense coord array in order to avoid duplications of coords.
But I prefer to preserve the original nums of points from a poindcloud.I just  take a rounding operation on the coords.So there may exsit some same coords.
How can I solve the problem？

--------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 130, in <module>
    sinput = ME.SparseTensor(features, coords=coordinates).to(device)
  File "/home/stevencui/anaconda3/lib/python3.6/site-packages/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg/MinkowskiEngine/SparseTensor.py", line 119, in __init__
    coords_manager.initialize(coords, coords_key)
  File "/home/stevencui/anaconda3/lib/python3.6/site-packages/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg/MinkowskiEngine/MinkowskiCoords.py", line 51, in initialize
    enforce_creation)
ValueError: A duplicate key found. Existing coord: [97, 273, 49, 0], new coord: : [97, 273, 49, 0]. If the duplication was intentional, use initialize_coords_with_duplicates.

**Comment by chrischoy** [comment]
Trying to provide two features for one coordinate is like providing two color values for one pixel. This is not possible to represent in a sparse tensor format. What you should do is to provide an average value for the duplicate coordinates and then simply copy the final value to the output points either with nearest neighbor scheme or with trilinear interpolation. To achieve the best performance on the ScanNet (http://kaldir.vc.in.tum.de/scannet_benchmark/semantic_label_3d), I simply use the nearest neighbor.
