### ISSUE TITLE
MinkowskiNet not learning anything on ModelNet40 Classification

### ISSUE THREAD

**Issue by Nicny** [StanfordVL/MinkowskiEngine#32]
I try to classify ModelNet40 using ResNet, but it seems to learn nothing and the loss can not go down. Here's the code I am using to run the network:

    criterion = nn.CrossEntropyLoss()
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = ResNet14(in_channels=1, out_channels=40, D=3).cuda()
    # model = vgg16(input_channel=1, num_classes=40, D=3).cuda()
    optimizer = Adam(model.parameters(), lr=1e-1)

    trainIterator = data.train_cls()
    validIterator = data.valid()
    print('#parameters', sum([x.nelement() for x in model.parameters()]))
    for epoch in range(10):
        model.train()
        i = 0
        start = time.time()
        for batch in trainIterator:
            optimizer.zero_grad()

            coords = batch[0]
            feat = batch[1]
            label = batch[2].to(device)

            sinput = ME.SparseTensor(feat, coords=coords).to(device)
            predictions = model(sinput)
            loss = criterion(predictions.F, label)
            i += 1
            print('Iteration: ', i, ', Loss: ', loss.item())
            loss.backward()
            optimizer.step()
        torch.save(epoch, 'epoch.pth')
        torch.save(model.state_dict(), 'model.pth')

The data prepration code is:

        def train_cls():
            return torch.utils.data.DataLoader(dataset_train_cls(),
                                               batch_size=20,
                                               collate_fn=collation_fn,
                                               num_workers=0,
                                               shuffle=True)

        def collation_fn(data_labels):
            coords, feats, labels = list(zip(*data_labels))
            coords_batch, feats_batch, labels_batch = [], [], []

            for batch_id, _ in enumerate(coords):
                N = coords[batch_id].shape[0]

                coords_batch.append(
                    torch.cat((torch.from_numpy(coords[batch_id]).int(),
                               torch.ones(N, 1).int() * batch_id), 1))
                feats_batch.append(torch.from_numpy(feats[batch_id]))
                labels_batch.append(torch.from_numpy(labels[batch_id]))

            # Concatenate all lists
            coords_batch = torch.cat(coords_batch, 0).int()
            feats_batch = torch.cat(feats_batch, 0).float()
            labels_batch = torch.tensor(labels_batch).long()

            return coords_batch, feats_batch, labels_batch

        def load_file(file_name, voxel_size):
            coords = np.loadtxt(file_name)
            feats = np.ones((coords.shape[0], 1))
            labels = np.loadtxt(file_name[:-3] + 'label').astype('int64')
            discrete_coords, unique_feats = ME.utils.sparse_quantize(
                coords=coords,
                feats=feats,
                labels=None,
                hash_type='ravel',
                set_ignore_label_when_collision=False,
                quantization_size=voxel_size)
            return discrete_coords, unique_feats, labels

        class dataset_train_cls(torch.utils.data.Dataset):
            def __init__(self):
                l1 = glob.glob('/home/zhang/桌面/SparseConvNet-master/data/train_pts/*.pts')
                self.path = l1
                print(len(self.path))

            def __len__(self):
                return len(self.path)

            def __getitem__(self, ind):
                curpath = self.path[ind]
                data = load_file(curpath, 0.001)
                return data

**Comment by chrischoy** [comment]
Please take a look at

https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/modelnet40.py

**Comment by chrischoy** [comment]
It gets 43% accuracy after 1k iterations.

**Comment by kkkkeeee** [comment]
Hi,

I tried to run examples/modelnet40.py on my desk. However, I got the following error. I didn't change anything in the code. Could you please tell me how to fix it? Thanks!

File "/home/keke/.conda/envs/py3-mink/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/keke/.conda/envs/py3-mink/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/keke/MinkowskiEngine/examples/modelnet40.py", line 462, in <module>
    train(net, device, config)
  File "/home/keke/MinkowskiEngine/examples/modelnet40.py", line 419, in train
    data_dict = train_iter.next()
  File "/home/keke/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/keke/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/keke/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/keke/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/keke/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/keke/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/keke/MinkowskiEngine/examples/modelnet40.py", line 295, in __getitem__
    vmax = vertices.max(0, keepdims=True)
  File "/home/keke/.conda/envs/py3-mink/lib/python3.7/site-packages/numpy/core/_methods.py", line 30, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by chrischoy** [comment]
```
ValueError: zero-size array to reduction operation maximum which has no identity.
```

It seems like the vertices array was empty. Did you complete the download process?

**Comment by kkkkeeee** [comment]
Yes. I deleted the previous Modelnet40 and its zip file and rerun "python -m examples.modelnet40" to download the dataset again in MinkowskiEngine directory. 

I got the exact same error. The mesh_file which causes the error is outputted, which is "./ModelNet40/mantel/train/mantel_0207.off". The vertices array length is 0.

~/MinkowskiEngine$ ls -l ./ModelNet40/mantel/train/mantel_0207.off
-rwxrwxr-x 1 keke keke 321978 Nov 27  2014 ./ModelNet40/mantel/train/mantel_0207.off

**Comment by chrischoy** [comment]
That is very strange. I just ran the modelnet40.py again after deleting the .tgz and the ModelNet40 directory and checked that the file is fine.

```
In [3]: pcd = o3d.io.read_triangle_mesh('mantel_0207.off')

In [4]: pcd.vertices
Out[4]: 
std::vector<Eigen::Vector3d> with 10340 elements.
Use numpy.asarray() to access data.
```

**Comment by kkkkeeee** [comment]
I finally solved it.

The open3D version is wrong in my machine. Before I installed open3d with "pip install open3d", which is version 0.7.0.0. I got the error "Read geometry::TriangleMesh failed: unknown file extension." when executing 

pcd = o3d.io.read_triangle_mesh('mantel_0207.off')

So I installed open3d using "conda install -c open3d-admin open3d", and it works now! The version is 0.8.0.0.

**Comment by chrischoy** [comment]
I see. Thanks for following up. Ill add some note on the documentation.

**Comment by chrischoy** [comment]
Here's the link to the ScanNet training: https://github.com/chrischoy/SpatioTemporalSegmentation/.

**Comment by chrischoy** [comment]
Closing the issue https://github.com/StanfordVL/MinkowskiEngine/commit/23d0021f5f55e863b2969c88f862c7d4feee73f7

**Comment by chronbird** [comment]
Hi @chrischoy ,
I find the same 'ValueError zero-size array to reduction operation maximum which has no identity', for the file monitor_0360 in the ModelNet40's train folder. Both open3d 0.8.0.0 and open3d 0.10.0.0 do not work, the ModelNet40 dataset is downloaded from https://modelnet.cs.princeton.edu/. Could you help with this issue? Thanks in advance.

**Comment by chrischoy** [comment]
I removed problematic models on the aligned ModelNet40.
