### ISSUE TITLE
python setup.y install error

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [StanfordVL/MinkowskiEngine#33]
Environment:
OS: Ubuntu 16.04
Cuda version: 9.0.176
CuDNN version: 7.0
Python version: 3.6.8
GCC version: 5.4.0

Error:
running install
running bdist_egg
running egg_info
writing MinkowskiEngine.egg-info/PKG-INFO
writing dependency_links to MinkowskiEngine.egg-info/dependency_links.txt
writing requirements to MinkowskiEngine.egg-info/requires.txt
writing top-level names to MinkowskiEngine.egg-info/top_level.txt
reading manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
writing manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'MinkowskiEngineBackend' extension
gcc -pthread -B /home/thanhnv/anaconda3/envs/tensorflow_gpu/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./ -I/home/thanhnv/anaconda3/envs/tensorflow_gpu/include/python3.6m/.. -I/home/thanhnv/.local/lib/python3.6/site-packages/torch/include -I/home/thanhnv/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/thanhnv/.local/lib/python3.6/site-packages/torch/include/TH -I/home/thanhnv/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/thanhnv/anaconda3/envs/tensorflow_gpu/include/python3.6m -c pybind/minkowski.cpp -o build/temp.linux-x86_64-3.6/pybind/minkowski.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MinkowskiEngineBackend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/thanhnv/anaconda3/envs/tensorflow_gpu/compiler_compat -L/home/thanhnv/anaconda3/envs/tensorflow_gpu/lib -Wl,-rpath=/home/thanhnv/anaconda3/envs/tensorflow_gpu/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/pybind/minkowski.o -Lobjs -L/usr/local/cuda/lib64 -lminkowski -lopenblas -lcudart -o build/lib.linux-x86_64-3.6/MinkowskiEngineBackend.cpython-36m-x86_64-linux-gnu.so
/home/thanhnv/anaconda3/envs/tensorflow_gpu/compiler_compat/ld: cannot find -lminkowski
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1`
`
Does anyone know which cause this error and how to fix?

**Comment by chrischoy** [comment]
Could you first install CUDA > v10.0 and try

```
make clean
python setup.py install
```

**Comment by NguyenVanThanhHust** [comment]
Tks you. But the problem is remained. I reinstalled Cuda. When i check with nvidia-smi,  i got NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1. Then i check cudnn, i got version : 7.5.1 . Does version of gcc matter ?

**Comment by chrischoy** [comment]
Could you put the entire output of the following command? I need to know what errors you get to help you.

‘’’
make clean
make
python setup.py install
‘’’

**Comment by sarsbug** [comment]
> Could you put the entire output of the following command? I need to know what errors you get to help you.
> 
> ‘’’
> make clean
> make
> python setup.py install
> ‘’’

you should make sure that your CUDA_HOME env setting is right

**Comment by NguyenVanThanhHust** [comment]
Thanks you all. I recheck every and discover that nvidia-smi just show wrong version of cuda. If i check with nvidia-smi, it might show cuda version 10.1. But when i check in usr/local/ i found my real cuda is 9.0. So i uninstalled all ( cuda, cudnn and nvidia-kernel) and reinstalled. Now it works. Tks you.
