### ISSUE TITLE
ImportError:_Z8cpu_gemmIfEv11CBLAS_ORDER15CBLAS_TRANSPOSES1_iiiT_PKS2_S4_S2_PS2_

### ISSUE THREAD

**Issue by GaoQiyu** [StanfordVL/MinkowskiEngine#36]
system: Ubuntu18.04.3 LTS 64x
memory: 16GB
cpu:Intel® Core™ i7-7700 CPU @ 3.60GHz × 8
gpu:GeForce GTX 1060 6GB/PCIe/SSE2
cuda: 10.1
python:3.7.4(pyenv)

ImportError: /home/user/.pyenv/versions/3.7.4/lib/python3.7/site-packages/MinkowskiEngine-0.2.7a4-py3.7-linux-x86_64.egg/MinkowskiEngineBackend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z8cpu_gemmIfEv11CBLAS_ORDER15CBLAS_TRANSPOSES1_iiiT_PKS2_S4_S2_PS2_

what should I do?

**Comment by chrischoy** [comment]
Hmm, it looks like the engine could not import functions in `src/math_functions.cpp` . Could you make sure that it compiled successfully?

```
cd MinkowskiEngine
make clean
make
python setup.py install
```
 Could you post the output after you run the above commands?

**Comment by GaoQiyu** [comment]
> Hmm, it looks like the engine could not import functions in `src/math_functions.cpp` . Could you make sure that it compiled successfully?
> 
> ```
> cd MinkowskiEngine
> make clean
> make
> python setup.py install
> ```
> 
> Could you post the output after you run the above commands?

hi ,I try to run make first then run python setup.py install and it works. 
Sorry to bother you
Thanks!

**Comment by chrischoy** [comment]
No problem. Glad it worked :)
