### ISSUE TITLE
MinkowskiEngineBackend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cusparseDcsrmv for Pytorch v1.3

### ISSUE THREAD

**Issue by GaoQiyu** [StanfordVL/MinkowskiEngine#37]
system: Ubuntu18.04.3 LTS 64x
memory: 15.6 GiB
cpu:Intel® Core™ i5-9400F CPU @ 2.90GHz × 6
gpu:GeForce RTX 2060/PCIe/SSE2
cuda: 10.1
python:3.7.4(pyenv)

python3.7/site-packages/MinkowskiEngine-0.2.7a4-py3.7-linux-x86_64.egg/MinkowskiEngineBackend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cusparseDcsrmv

I tried to add libcusparse.so path to LD_LIBRARY_PATH, but it doesn't work ,I dont know how to deal with it.

**Comment by chrischoy** [comment]
Can you print the results of 

```
cd MinkowskiEngine
ldd build/lib.linux-x86_64-3.7/MinkowskiEngineBackend.cpython-37m-x86_64-linux-gnu.so
echo $(dirname $(dirname $(which nvcc)))
echo $LD_LIBRARY_PATH
echo $CUDA_HOME
```

**Comment by GaoQiyu** [comment]
1
`ldd build/lib.linux-x86_64-3.7/MinkowskiEngineBackend.cpython-37m-x86_64-linux-gnu.so`
	`linux-vdso.so.1 (0x00007fff6a58b000)
	libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007f4d6c382000)
	libcudart.so.10.1 => /usr/local/cuda/lib64/libcudart.so.10.1 (0x00007f4d6c106000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4d6bd7d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4d6bb65000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4d6b774000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4d6edfc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4d6b3d6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4d6b1b7000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f4d6add8000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4d6abd4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4d6a9cc000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f4d6a78c000)`
__
2
`which nvcc`
`/usr/local/cuda/bin/nvcc`

3
`echo `$LD_LIBRARY_PATH`
`/usr/local/cuda/lib64`

4 
`echo $CUDA_HOME`
`/usr/local/cuda`

**Comment by chrischoy** [comment]
Hmm it seems like this is due to the $CUDA_HOME. Similar to https://github.com/StanfordVL/MinkowskiEngine/issues/12

This is because I get the CUDA_HOME from pytorch here https://github.com/StanfordVL/MinkowskiEngine/blob/master/Makefile#L44.

I assumed that pytorch would do some basic sting preprocessing, but obviously not.

Please set the CUDA_HOME to

```
export CUDA_HOME=/usr/local/cuda
```

I'll find more permanent solution

**Comment by chrischoy** [comment]
Ah forgot to mention that you need to compile from scratch


cd MinkowskiEngine
make clean
export CUDA_HOME=$(dirname $(dirname $(which nvcc))); python setup.py install

**Comment by GaoQiyu** [comment]
sorry I tried , but it doesn't work.
The same error

**Comment by chrischoy** [comment]
Could you comment out the https://github.com/StanfordVL/MinkowskiEngine/blob/master/Makefile#L5 and 

```
make clean
make
python setup.py install
```

and put the result on https://pastebin.com/ and share the link here?

**Comment by GaoQiyu** [comment]
It exceeded the maximum paste size of 512 kilobytes per paste.
So I create a .html file, you can download and have a look
[https://drive.google.com/open?id=1O3u4vsbhCg5SirYkU03riSUw4UK3EstI](url)

**Comment by chrischoy** [comment]
Thanks for sharing the output.

If this is a CUDA version problem, you should be able to run the CPU_ONLY build.
If the CPU_ONLY build also fails with different error, then there is another hidden problem.

1. Could you build with CPU_ONLY compile first to make sure that it works? Again, you would need 

Uncomment line 8 of the Makefile
Uncomment line 66 of setup.py.
make clean
python setup.py install.
python -m tests.coords


2. Could you use pytorch v1.2? I got some report that MinkowskiEngine doesn’t work with 1.3, but I could not reproduce the error.


3. The cuda API mentioned that the function will be deprecated in the next major release https://docs.nvidia.com/cuda/cusparse/index.html#csrmv 

However, your ldd results show that you are using 10.1 so it shouldn’t be a problem. Regardless, I’ll update the code.

**Comment by GaoQiyu** [comment]
It's pytorch version's problem. I tried pytorch==1.2.0 and it works!
Thanks!

**Comment by chrischoy** [comment]
Great!. I'll update the library to work with pytorch v1.3.

**Comment by chrischoy** [comment]
Hmm I still cannot reproduce on new devices. It just works on pytorch v1.3. Do you have different CUDA versions installed on the device?

**Comment by chrischoy** [comment]
Hmm it seems that pytorch updated the binaries and might be the reason why it works. @GaoQiyu could you try the newer pytorch by force installing the latest binaries?

**Comment by GaoQiyu** [comment]
ok, I will try it today.
and ..... can you tell me how to set collision labels ？

**Comment by GaoQiyu** [comment]
lib/python3.7/site-packages/MinkowskiEngine-0.2.7a4-py3.7-linux-x86_64.egg/MinkowskiEngineBackend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cusparseDcsrmv

the same error
have you try pyenv?it always ..
if not the problem of pyenv, maybe something wrong with my system

**Comment by HenrryBryant** [comment]
With Torch v1.3, the error occurs if you don't use Conda, you have to install Torch V1.2 instead.

**Comment by chrischoy** [comment]
We tried the pytorch 1.3.1 with MinkowsiEngine on Arch linux without conda and successfully compiled and ran the engine without a problem.

I cannot reproduce this error for now.
