### ISSUE TITLE
C++ version problem

### ISSUE THREAD

**Issue by GaoQiyu** [StanfordVL/MinkowskiEngine#39]
hi, when I compile it on the server, I face another problem.
I think maybe the C++ version problem.
Because usually I compile it with /usr/include/c++/7 and it works, but this time it uses /usr/include/c++/6.
I found there exists both c++/6 and c++/7 in /usr/include on server
here is the output of the terminal
[https://drive.google.com/open?id=1ONYSu36mpwCCw95iHAzf5JQlgatVV5sZ](url)

If it is the problem of c++ version, what should I do to modify?

**Comment by chrischoy** [comment]
Thanks for reporting the issue.

You would have to modify the Makefile line 10 to

CXX := /path/to/g++-7

**Comment by GaoQiyu** [comment]
it still use c++/6  and output the same error, maybe not this problem?

**Comment by chrischoy** [comment]
The include path seems to be incorrect as well

Try to find the C++ v7 include files and export

export CPATH=/path/to/include/c++/7

Do not use the /path/to/include as is. Modify it to the correct path.

**Comment by GaoQiyu** [comment]
I tried CXX := /path/to/g++-7 and it works a little.
but there arise a new problem
`/usr/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
`
but if I use g++ 6 and the same error as mentioned before

**Comment by GaoQiyu** [comment]
I fix above error by reinstall cuda on server, but....another error
`1. /tmp/tmpxft_00007d97_00000000-5_pruning.compute_61.cudafe1.stub.c:12:182: error: ‘__args_arr’ was not declared in this scope

2.  /tmp/tmpxft_00007dc8_00000000-5_pooling_avg.compute_61.cudafe1.stub.c:20:93: error: ‘__args_idx’ was not declared in this scope

3. /usr/include/c++/7/tuple:497:244: error: wrong number of template arguments (5, should be 2)

4. /usr/include/c++/7/tuple:504:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = std::tuple<at::Tensor, at::Tensor, at::Tensor, long int>&&; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor, long int}]’ not a return-statement
    
5. /usr/include/c++/7/tuple:485:67: error: mismatched argument pack lengths while expanding ‘std::is_constructible<_Elements, _UElements&&>’
       return __and_<is_constructible<_Elements, _UElements&&>...>::value;
 6. /usr/include/c++/7/tuple:491:65: error: mismatched argument pack lengths while expanding ‘std::is_convertible<_UElements&&, _Elements>’
       return __and_<is_convertible<_UElements&&, _Elements>...>::value;
and lots of pybind error...}
`

**Comment by chrischoy** [comment]
Hmm, not sure why you get these error messages.

When you change the compiler or cuda version, you have to make from scratch.
Try

```
make clean;
python setup.py install
```

**Comment by GaoQiyu** [comment]
Finally I fix it, It 's the problem of cuda version mix.
I install cuda 10.0, but nvcc and some library still old 9.1
my mistake

**Comment by chrischoy** [comment]
Great! Closing the issue
