### ISSUE TITLE
scannet training and inference code

### ISSUE THREAD

**Issue by mingminzhen** [StanfordVL/MinkowskiEngine#4]
Is it possible to make training and inference code for scannet dataset public? It will be very helpful.

**Comment by chrischoy** [comment]
Hi, we are working on release. We have a separate repo for this and will update the issue when we release it!

**Comment by BestSonny** [comment]
> Hi, we are working on the release. We have a separate repo for this and will update the issue when we release it!

@chrischoy Is there any estimated date for the release? Thank you very much.

**Comment by chrischoy** [comment]
Hi everyone,

I am very sorry for the delay. I couldn't seem to find time to sit down and refactor the code. I will try to release it soon, but training is very simple. However, try to incorporate the following components to reproduce the numbers on the paper:


1. Chromatic jitter (Gaussian on color)
2. Chromatic translation (Add a constant to all voxels in a scene)
3. Random rotation (all 3D rotation, but mostly along the gravity direction)
4. Random scaling of a scene
5. Spatial translation (adding a constant vector to all coordinates)

Also, use the rotation average (extract features from various rotated scenes and averaging the final logit scores) when you evaluate the final semantic segmentation mIoU.

Happy research everyone!

**Comment by chrischoy** [comment]
Here's a simple tutorial for working with Pytorch dataset and dataloader: https://stanfordvl.github.io/MinkowskiEngine/demo/training.html#

**Comment by wbhu** [comment]
Thanks for the excellent work. 
But what is the exact MinkowskiNet42 configuration, there are only something like MinkUNet34, MinkUNet50 ...?

**Comment by chrischoy** [comment]
That is the MinkUNet34, which has 43 layers. Sorry for the confusion, but I
implemented these residual networks based on the default res18, res34, etc.
thats why I kept the name like this. The examples/indoor.py uses the same
network.

**Comment by chrischoy** [comment]
Hi, I made the scannet training public. https://github.com/chrischoy/SpatioTemporalSegmentation/
It might take few more days to cleanup, but the scannet training works.

**Comment by filaPro** [comment]
> Hi everyone,
> 
> I am very sorry for the delay. I couldn't seem to find time to sit down and refactor the code. I will try to release it soon, but training is very simple. However, try to incorporate the following components to reproduce the numbers on the paper:
> 
> 1. Chromatic jitter (Gaussian on color)
> 2. Chromatic translation (Add a constant to all voxels in a scene)
> 3. Random rotation (all 3D rotation, but mostly along the gravity direction)
> 4. Random scaling of a scene
> 5. Spatial translation (adding a constant vector to all coordinates)
> 
> Also, use the rotation average (extract features from various rotated scenes and averaging the final logit scores) when you evaluate the final semantic segmentation mIoU.
> 
> Happy research everyone!

Hi @chrischoy ,

Does this mean that metrics from the paper can be only obtained with test time augmentation?
