### ISSUE TITLE
TS-CRF

### ISSUE THREAD

**Issue by GaoQiyu** [StanfordVL/MinkowskiEngine#44]
I trained ResUNetIN14 with Adam(lr=0.1,weight_decay=1e-4,) on S3DIS fold1 split
but it only achieve 30%mIOU......
Then I test the trained model and found points on the same object have multiple labels
I think maybe the reason is no CRF?
sorry I didn't found out where the implement of TS-CRF in code

**Comment by chrischoy** [comment]
Instance Norm is worse than BN. SGD is better than Adam if you use BN.
CRF for static scenes don't really help much.
Also, it is important to have set the collision labels as ignore_label OR use higher resolution.

Can you repost this on the https://github.com/chrischoy/SpatioTemporalSegmentation? This repository doesn't have the ResUNetIN or Stanford training code.

**Comment by chrischoy** [comment]
Moving the issue to https://github.com/chrischoy/SpatioTemporalSegmentation/issues/10
