### ISSUE TITLE
error when use convolution after generating new coords

### ISSUE THREAD

**Issue by zjhthu** [StanfordVL/MinkowskiEngine#47]
Hi, I got an error `RuntimeError: src/coords_kernelmaps.hpp:50, assertion (existsCoordsKey(in_coords_key) and existsCoordsKey(out_coords_key)) faild. The coords map doesn't exist for the given coords_key.  in_coords_key:  1681692777 , out_coords_key:  592599417076398501` when using convolution after generating new coords.

This can be reproduced by modifying the test code in `tests/pruning.py`:
```
conv_tr1 = MinkowskiConvolutionTranspose(
            channels[0],
            channels[1],
            kernel_size=3,
            stride=2,
            generate_new_coords=True,
            dimension=D).double()
conv1 = MinkowskiConvolution(channels[1], channels[1], kernel_size=3, dimension=D).double()


out1 = conv_tr1(input)
out1 = conv1(out1)
```

**Comment by chrischoy** [comment]
Thanks for reporting the issue! I just fixed it and added your convolution to the pruning example.
