### ISSUE TITLE
GlobalMaxPooling

### ISSUE THREAD

**Issue by HenrryBryant** [StanfordVL/MinkowskiEngine#48]
hi Chirs,

Do you have a plan to support global max pooling?

**Comment by chrischoy** [comment]
Okay, sounds useful, I'll look into it after the deadline.

**Comment by BestSonny** [comment]
@HenrryBryant You may want to check my posted solution. I posted it here. Let me know if have any questions.

**Comment by chrischoy** [comment]
The PR #49 has been merged to the master through minor formatting changes #50.

Thanks for the contribution @BestSonny !

**Comment by HenrryBryant** [comment]
> @HenrryBryant You may want to check my posted solution. Let me know if have any problems regarding the implementation. **I can not guarantee that it is 100% correct**, but you can have these to start with

Wow, I'm just working on it. Thank you so much!
