### ISSUE TITLE
`thrust::system::system_error` when `sparse_quantize` called with label

### ISSUE THREAD

**Issue by BuaaTang** [StanfordVL/MinkowskiEngine#5]
Hi, 

When I run codes below

```python3
import MinkowskiEngine as ME, MinkowskiEngine.utils as ME_utils
import numpy as np

coords = np.random.rand(10000, 3) * 100
feats = np.random.rand(10000, 3)
labels = np.ones((10000, 1))
print(ME_utils.sparse_quantize(coords, feats=feats, labels=labels))
```
I got error:
```shell
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: invalid argument
```

But code above works fine after I reduced the size of coords (100, such as) or just removed the argument 'labels'.

Is there any suggestion?

THX!

**Comment by chrischoy** [comment]
Thanks for submitting the issue. I can confirm that this is reproducible in my setup as well.

For now, you can use like the [`examples/indoor.py#L107`](https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/indoor.py#L107).

```
inds = ME_utils.sparse_quantize(coords)
return coords[inds], feats[inds], labels[inds]
```

This is how I trained all my recent models that is top-ranked on the ScanNet 3D semantic segmentation benchmark. However, I'll fix this issue in few days.

**Comment by chrischoy** [comment]
It turns out that `thrust` 1.9 is not compatible with the old code for some reasons that are not specified in the API. The simplest `sort_by_key` without a tuple iterator does not work giving the error

```
CUDA error 11 [/usr/local/cuda/include/thrust/system/cuda/detail/cub/device/dispatch/dispatch_radix_sort.cuh, 976]: invalid argument
CUDA error 11 [/usr/local/cuda/include/thrust/system/cuda/detail/cub/device/dispatch/dispatch_radix_sort.cuh, 1183]: invalid argument
CUDA error 11 [/usr/local/cuda/include/thrust/system/cuda/detail/cub/device/dispatch/dispatch_radix_sort.cuh, 1283]: invalid argument
```

This would take more longer term investigation and would require working with thrust. I'll make an alternative CPU based method as the default voxelization method for now.
