### ISSUE TITLE
usage of MinkowskiConvolutionTranspose when given output coords

### ISSUE THREAD

**Issue by zjhthu** [StanfordVL/MinkowskiEngine#51]
It seems `MinkowskiConvolutionTranspose` supports specifying coordinates for the output, but I do not find a way to pass the output coordinates. 

As the [document](https://stanfordvl.github.io/MinkowskiEngine/convolution.html#MinkowskiEngine.MinkowskiConvolutionTranspose) says, we need to pass `out_coords_key ` to the function, but the `out_coords_key` seems only contains dimension and tensor stride information, and does not contain coordinates information, am I right? Should we also pass the `CoordsManager` object to the function?

**Comment by chrischoy** [comment]
Hmm currently the API is supported, but it is not very user friendly. Let me update the functions to support this in a cleaner fashion.

**Comment by chrischoy** [comment]
On the latest commit, I've added `MinkowskiConvolutionOnCoords` and `MinkowskiConvolutionTransposeOnCoords`.

These are the same classes as the regular convolution and transposed convolution except that it takes additional arguments for coordinates.

```python
 conv = MinkowskiConvolutionOnCoords(
            in_channels,
            out_channels,
            kernel_size=3,
            stride=1,
            dimension=D)
...
output = conv(sparse_tensor, specified_out_coords_or_sparse_tensor_with_the_out_coords)
```

Please refer to the example [tests/conv_on_coords.py](https://github.com/StanfordVL/MinkowskiEngine/blob/master/tests/conv_on_coords.py) for the usage.

**Comment by zjhthu** [comment]
Thanks, it solves my problem!

**Comment by chrischoy** [comment]
The provided function is now deprecated after 13 days :)

Now, you can do the same on the regular `MinkowskiConvolution[Transpose]` and `Minkowski*Pooling` layers.

**Comment by zjhthu** [comment]
ok, thanks for reminding me.
