### ISSUE TITLE
build error: Set TBB_PREVIEW_GLOBAL_CONTROL before including global_control.h

### ISSUE THREAD

**Issue by zjhthu** [StanfordVL/MinkowskiEngine#56]
```
In file included from src/concurrent_coordsmap.hpp:4:0,
                 from src/concurrent_coordsmap.cpp:1:
/usr/include/tbb/global_control.h:25:2: error: #error Set TBB_PREVIEW_GLOBAL_CONTROL before including global_control.h
````
I use Ubuntu 16.04, libtbb-dev 4.4, python3.6, pytorch1.3

**Comment by chrischoy** [comment]
It seems that conda installs the latest TBB which is tag `2019_U8` or `TBB_INTERFACE_VERSION` 11008.

They removed the `TBB_PREVIEW_GLOBAL_CONTROL` from 11004 or [`2019_U4`](https://github.com/intel/tbb/blob/2019_U4/include/tbb/global_control.h).

Could you try conda in the meantime? I'll check whether tbb 4.4 is compatible, but I suspect 3 year old code might be either slow or doesn't support some functions.

**Comment by s9xie** [comment]
If you use conda, it is indeed the TBB version problem - I resolved the problem by:
```
conda config --add channels conda-forge
conda install tbb=2019.9 tbb-devel=2019.9
```
The default conda package will pull the 2019.3 version which causes the mismatch

**Comment by chrischoy** [comment]
Ah thanks for the tip. I only tested this on ubuntu 19.04 which seems to be installing the U4 by default. I'll update the conda installation instruction.

**Comment by zjhthu** [comment]
thanks, it works now
