### ISSUE TITLE
GCC version should >5

### ISSUE THREAD

**Issue by lshiwjx** [StanfordVL/MinkowskiEngine#57]
GCC versions < 5 do not support std::is_trivially_copyable from the C++11 standard.

**Comment by chrischoy** [comment]
I see thanks for pointing this out. I'll put this in the requirements and the Makefile.

**Comment by chrischoy** [comment]
https://github.com/StanfordVL/MinkowskiEngine/commit/61c90a05abef048b8f4ac6b83eb3b8ff940b3fcf
