### ISSUE TITLE
Feature map concatenation

### ISSUE THREAD

**Issue by HughRunyan** [StanfordVL/MinkowskiEngine#58]
Is it possible to do so from different underlying point sets? Like, concatenate a feature map of X x Y x Z x nfeatures from one point cloud to another of the same dimensions.

**Comment by chrischoy** [comment]
It is not supported, but I plan to support sparse tensor addition. The features have to have the same dimension however.

**Comment by chrischoy** [comment]
I made [`MinkowskiUnion`](https://stanfordvl.github.io/MinkowskiEngine/union.html). Would this function be of use in your application?

**Comment by HughRunyan** [comment]
Apologies for radio silence, holidays stuff.

I think it's quite close! I didn't explain my application very clearly. Lets say I have point cloud A, whose points I want segmented, and point cloud B, which is a different point cloud of the same scene, i.e. the point locations are different but the underlying geometry is the same and both point clouds share a coordinate system/frame of reference. I want to derive feature maps from both A and B, and then transfer B to A. In my application, only A is to be segmented, and while B might be incomplete relative to A it is at higher resolution, so I need to build a network that inputs B at say 1024 x 1024 x 1024, reduces it to a feature map of 256 x 256 x 256, then inputs A at 256 x 256 x 256, concatenates the features of B to A at grid locations of A that contain A point cloud points, and then performs standard UNet segmentation. 

The architecture is quite similar to simply adding features to each A input point -- instead of the 3 RGB input features, there would be 3 + 29 or 3 + 61 or whatever. It seems much simpler to do this operation in voxel space as a concatenation than to do some kind of nearest point matching/interpolation between point cloud points. 

I hope that makes sense, it's difficult to explain with only words, apologies. Thanks for your time, consideration, and any assistance!

**Comment by chrischoy** [comment]
Cant you use PoolingTranspose?

**Comment by HughRunyan** [comment]
I'm not sure! I see that I can give it out_coords_key. So if I were to do a couple of conv layers to get a feature map of point cloud B, I could unpool those features to the point coordinates of A. Then I could concat that to the 2D feature matrix of point cloud A. Is that what you were envisioning? Sounds feasible, I'll try it and get back to you with results

**Comment by chrischoy** [comment]
By default, the output will be automatically set correctly if you use a U-net structure. The MinkowskiEngine saves unique sets of coordinates at each tensor stride and reuse. However, if there are more than one sets of coordinates for the same tensor stride, it will use the first set registered on the system.

**Comment by HughRunyan** [comment]
Hmm. I'm not entirely sure what you mean by "stride"? Are you using it in the standard way, as in "the distance between convolutional kernel center locations"? Are you saying I could input two separate tensors with two separate point cloud coordinates to a single conv layer and receive a single output for just one set of coordinates? That seems a little strange but you wrote the code. Are you using "coordinates" to refer to point cloud point locations or voxel grid locations? In the architecture I am trying to construct, the first input will be what I've been calling point cloud B, the higher-resolution image-depth-map-derived cloud. Point cloud A, which I want segmented, will enter second and be combined with features derived from B.

**Comment by HughRunyan** [comment]
I haven't started augmenting your dataloader code, but my assumption is I would design it to load pairs of point clouds (as opposed to two separate dataloaders), so the choice of which is "first" is semi-arbitrary, but computations will be done to point cloud B before A. I could conceivably do one conv layer on A first if establishing it as first is important.

**Comment by HughRunyan** [comment]
Maybe a little background will help. I have a point cloud model made with photogrammetry/structure from motion (SfM). So I have a 3D model as well as images and camera pose info -- I know their geometric relationship. I have two sets of photos, one from an 18mm wider-angle lense and another from a 55mm narrower-angle, which produces higher-resolution images. The models were only built with 18mm, so there is additional detail information contained in the 55mm images I would like to extract. Because I have depth maps of the images from the SfM process, I can treat those higher-resolution images as point clouds. I would like to build a model that considers precisely-geometrically-aligned information from the 55mm image depth maps (at least one, but preferably more) when segmenting the 3D models. Because of memory limitations, I currently input 1m^2 of model point cloud at a time, so the area under consideration is approximately equivalent to that covered by a single image.

**Comment by chrischoy** [comment]
I updated the function `MinkowskiPoolingTranspose` to take additional `coords` argument to specify the output coordinate with ease.

```python
pool_transpose = MinkowskiPoolingTranspose(...)
a = SparseTensor(...)
A = net(a)
b = SparseTensor(..., coords_manager=A.coords_man)  # Must share the coords manager
B = pool_transpose(b, A)  # this will generate B on coordinates of A
C = ME.cat((A, B))
```

**Comment by HughRunyan** [comment]
Thanks so much! I am in the process of investigating. Since updating to your new version, this line

```
a=quantized_coords[inds]
```

produces an array of dims (n_points, n_features, n_features) and throws an error. It used to be (n_points, n_features) and not throw an error. I'm currently toggling back and forth between containers with the exact same code -- old one runs, new one doesn't. Apologies if syntax for you is slightly different. Any idea what's going on? I'll look into it tomorrow, thanks for your help to this point, I appreciate it.

**Comment by chrischoy** [comment]
You should use https://stanfordvl.github.io/MinkowskiEngine/utils.html#MinkowskiEngine.utils.sparse_quantize

**Comment by HughRunyan** [comment]
How exactly do you envision ``` b = SparseTensor(..., coords_manager=A.coords_man)  # Must share the coords manager``` working? I tried just using B, as in ```B.coords_man = A.coords_man```, throws error. Also tried variations on ```b = ME.SparseTensor(coords=b.coords, feats=b.feats, coords_manager=A.coords_man)``` and ```b = ME.SparseTensor(coords=torch.zeros(1), feats=torch.zeros(1), coords_manager=A.coords_man)```, more errors.

**Comment by chrischoy** [comment]
You need to set the tensor stride right or use force_creation.

https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/sparse_tensor_basic.py#L73

**Comment by HughRunyan** [comment]
I'm getting ```RuntimeError: CUSPARSE_STATUS_INVALID_VALUE at src/math_functions.cu:230``` from the ```out = self.pool_transpose(out_B, out_A)``` step.

I'm using the same input cloud for A and B. A is voxel_size 1/100, B is 1/800. B enters, then goes through 

```
        self.inplanes = self.INIT_DIM
        
        self.conv0p1s1_hr = ME.MinkowskiConvolution(
            in_channels, self.inplanes, kernel_size=5, dimension=D)

        self.bn0_hr = ME.MinkowskiBatchNorm(self.inplanes)

        self.conv1p1s2_hr = ME.MinkowskiConvolution(
            self.inplanes, self.inplanes, kernel_size=2, stride=2, dimension=D)
        
        self.bn1_hr = ME.MinkowskiBatchNorm(self.inplanes)

        self.block1_hr = self._make_layer(self.BLOCK, 32,
                                       self.LAYERS[0])

        self.conv2p2s2_hr = ME.MinkowskiConvolution(
            self.inplanes, self.inplanes, kernel_size=2, stride=2, dimension=D)
        self.bn2_hr = ME.MinkowskiBatchNorm(self.inplanes)

        self.block2_hr = self._make_layer(self.BLOCK, 29,
                                       self.LAYERS[1])
        
        self.pooling = ME.MinkowskiPoolingTranspose(kernel_size=2, stride=1, dimension=D)

```

Which is just the input layer and first two downsampling layers copied from your code, but I hardcoded nplanes to be 32 at all steps (except 29 at the end, so I can add RGB)

**Comment by chrischoy** [comment]
It seems to work fine for me.

```python
    config = parser.parse_args()
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    voxel_size = 0.16
    C_low, F_low = generate_input_sparse_tensor(
        config.file_name, voxel_size=voxel_size)

    voxel_size = 0.02
    C_high, F_high = generate_input_sparse_tensor(
        config.file_name, voxel_size=voxel_size)

    D, inplanes = 3, 32
    B_net = nn.Sequential(
        ME.MinkowskiConvolution(3, inplanes, kernel_size=5, stride=2, dimension=D),
        ME.MinkowskiBatchNorm(inplanes), ME.MinkowskiReLU(),
        ME.MinkowskiConvolution(
            inplanes, inplanes, kernel_size=2, stride=2, dimension=D),
        ME.MinkowskiBatchNorm(inplanes), ME.MinkowskiReLU(),
        ME.MinkowskiConvolution(
            inplanes, inplanes, kernel_size=2, stride=2, dimension=D),
        ME.MinkowskiBatchNorm(inplanes), ME.MinkowskiReLU(),
        ME.MinkowskiPoolingTranspose(kernel_size=2, stride=1,
                                     dimension=D)).to(device)

    A = ME.SparseTensor(F_low, coords=C_low, tensor_stride=8).to(device)
    B = ME.SparseTensor(F_high, coords=C_high, coords_manager=A.coords_man).to(device)

    B_down = B_net(B)
    print(A.coords_key == B_down.coords_key)
    print(B_down.tensor_stride)
    C = ME.cat((A, B_down))
    print(C)
```


```
True
[8, 8, 8]
SparseTensor(
  Coords=tensor([[ 7,  4,  0,  0],
        [ 6,  4,  1,  0],
        [ 6,  4,  0,  0],
        ...,
        [53, 27, 11,  0],
        [53, 27, 12,  0],
        [53, 27, 14,  0]], dtype=torch.int32)
  Feats=tensor([[-0.0922, -0.1353, -0.1902,  ...,  0.0229,  0.0000,  0.0000],
        [-0.3510, -0.3745, -0.3941,  ...,  0.0229,  0.0000,  0.0000],
        [-0.4294, -0.4098, -0.4255,  ...,  0.0229,  0.0000,  0.0000],
        ...,
        [ 0.0569,  0.0216, -0.0608,  ...,  0.0457,  0.0000,  0.0000],
        [ 0.0373, -0.0294, -0.0765,  ...,  0.0457,  0.0000,  0.0000],
        [ 0.0176, -0.0569, -0.2333,  ...,  0.0457,  0.0000,  0.0000]],
       device='cuda:0', grad_fn=<CatBackward>)
  coords_key=< CoordsKey, key: 2212413213707219135, tensor_stride: [8, 8, 8] in dimension: 3 >                                                                                              
  tensor_stride=[8, 8, 8]
  coords_man=< CoordsManager
        Number of Coordinate Maps: 4
                Coordinate Map Key: 16908437251554604741, Size: 59999
                Coordinate Map Key: 13165352224437222115, Size: 15431
                Coordinate Map Key: 2212413213707219135, Size: 3831
                Coordinate Map Key: 15034981587763204738, Size: 161890
        Number of Kernel Maps: 4
                Kernel In-Out Map Key: 3550008150608628539, Size: 48
                Kernel In-Out Map Key: 17205248851024808945, Size: 1260638
                Kernel In-Out Map Key: 16227571178075280726, Size: 7649
                Kernel In-Out Map Key: 670309049195216561, Size: 59999 >
)
```
