### ISSUE TITLE
setup.py file seems broken

### ISSUE THREAD

**Issue by sandippurnapatra** [StanfordVL/MinkowskiEngine#59]
Hi tried to set it up in colab but it was unable to recognize setup.py file from the 'MinkowskiEngine'.

**CODE:** !git clone https://github.com/StanfordVL/MinkowskiEngine.git
!cd MinkowskiEngine && /usr/local/bin/python setup.py install

**ERROR:** "fatal: destination path 'MinkowskiEngine' already exists and is not an empty directory.
python3: can't open file 'setup.py': [Errno 2] No such file or directory"

**Comment by chrischoy** [comment]
This is a user error. Please read the error and fix by yourself.
