### ISSUE TITLE
robin_hood::map overflow when using MinkowskiConvolutionTranspose for some data

### ISSUE THREAD

**Issue by zjhthu** [StanfordVL/MinkowskiEngine#62]
I get `RuntimeError: robin_hood::map overflow` for some data, here is a simple debug code:

```
import MinkowskiEngine as ME
import torch

coords = torch.load('coarse_volume_C')
feat = torch.load('coarse_volume_F')
volume = ME.SparseTensor(feat, coords=coords, tensor_stride=2).to('cuda')
upConv = ME.MinkowskiConvolutionTranspose(32, 32, kernel_size=2, stride=2, generate_new_coords=True, dimension=3).cuda()
volume = upConv(volume)
```

[debug.tar.gz](https://github.com/StanfordVL/MinkowskiEngine/files/3968701/debug.tar.gz)

**Comment by chrischoy** [comment]
I can reproduce the error on my setup as well. Let me look into this problem.

**Comment by chrischoy** [comment]
It was due to the hash map giving errors aggressively. Preallocating larger size resolved the issue.

**Comment by zjhthu** [comment]
thanks for the quick fix.
