### ISSUE TITLE
How to average the features of duplicate coordinates?

### ISSUE THREAD

**Issue by lshiwjx** [StanfordVL/MinkowskiEngine#67]
I notice that the MinkowskiEngine.utils.sparse_quantize() will remove the duplicate coordinates and features. 

How can I average the features of duplicate coordinates?

**Comment by lshiwjx** [comment]
```
import MinkowskiEngine as ME
coords = np.array([[0,1], [0, 1]])
feas = np.array([[2, 3], [4, 5]])
cs, fs = ME.utils.sparse_quantize(coords, feas)

```
The cs is [[0, 1]] and fs is [[2, 3]]. 
I hope the fs should be [[3, 4]].

**Comment by chrischoy** [comment]
Currently, this is not supported, but I did not see performance degradation with removing duplicated features. In many cases, averaging color is not a good idea if there is a boundary. Rather making the label to `ignore_label` if there are label collision is more important. [`sparse_quantize`](https://stanfordvl.github.io/MinkowskiEngine/utils.html#MinkowskiEngine.utils.sparse_quantize) allows you to mask the labels if there are collosions.

**Comment by chrischoy** [comment]
It is now supported with `SparseTensor(..., quantization_mode=ME.SparseTensorQuantizationMode.UNWEIGHTED_AVERAGE)`. Please refer to the [`examples/indoor.py`](https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/indoor.py#L138) for the example.
