### ISSUE TITLE
Error when running indoor.py

### ISSUE THREAD

**Issue by vevenom** [StanfordVL/MinkowskiEngine#69]
Hi,

I am trying to test MinkowskiEngine. When simply running `python -m examples.indoor`, I am getting the following error:

> ... in sparse_collate
>     bcoords[s:s + cn, :D] = coord
> RuntimeError: expand(torch.IntTensor{[9941, 3, 3]}, size=[9941, 3]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)
> 
> 

Any idea what might be causing this issue?

Thank you for your assistance

Update:

`load_file(...)` seems to return coordinates and featrues of shape [9941, 3, 3] but `ME.utils.sparse_collate(...)` seems to expect the following shape [9941, 3]

**Comment by vevenom** [comment]
Setting `return_index=True` when invoking `sparse_quantize` did the trick. Is it possible that the `indoor.py` is outdated?

**Comment by chrischoy** [comment]
Thanks for submitting the issue. Yes, the indoor.py is outdated and will be updated.

**Comment by chrischoy** [comment]
Fixed on https://github.com/StanfordVL/MinkowskiEngine/commit/148d77c655f67a08986036d2af8c9fa31d21175e
