### ISSUE TITLE
How to get the coords index of previous coords after convolution with stride more than one

### ISSUE THREAD

**Issue by wbhu** [StanfordVL/MinkowskiEngine#70]
Hi,

If we apply a stride 2 convolution on a sparse tensor x to get a new sparse tenseor y, than the number  of coords of y should be less than x, how can we get the current index of coords of x, such that x.coords[index] == y.coords?

Thanks a lot!

**Comment by chrischoy** [comment]
When generating the strided map, I use floor to make all the generated coords divisible by the stride. In this case, there are many coords that are not equal to the strided coords. What behavior are you looking for? Do you want exact coords only? Or do you want all coords that map to the strided coords using floor?

**Comment by wbhu** [comment]
Thanks for your quick reply. I want all coords that map to the strided coords using floor. In detail, I have some feature that is associate with the coords, but this feature can not be convolved, so after strided covolution I want to extract the new feature cooresponding to the the new coords. If i can get the index, then this problem can be solved.

**Comment by chrischoy** [comment]
I added the function `get_coords_map(in_tensor_stride, out_tensor_stride)`.

Usage:

```python
sinput = SparseTensor(...)
soutput = stride_2_conv(sinput)

cm = sinput.coords_man # or soutput.coords_man. Doesn't matter.
ins, outs = cm.get_coords_map(1, 2)
inc = cm.get_coords(1)
outc = cm.get_coords(2)
for i, o in zip(ins, outs):
    print(f"{i}: ({inc[i]}) -> {o}: ({outc[o]})")
```

**Comment by wbhu** [comment]
That's great. Thanks for your help.
