### ISSUE TITLE
Element-wise multiplication/division/addition/subtraction

### ISSUE THREAD

**Issue by BestSonny** [StanfordVL/MinkowskiEngine#72]
@chrischoy  Just want to know whether we can support element-wise multiplication/division/addition/subtraction between two sparse tensors at the same coordinate locations (even with two different coordinate managers). Currently, it seems that the addition is supported already by the MinkowskiUnion.

**Comment by BestSonny** [comment]
For example,
```python
x1 = ME.SparseTensor(x, coordinate=y) # manager one
x2 = ME.SparseTensor(x, coordinate=y) # manager two

# not correct as the arrangement of feature is shuffled for each sparse tensor)
# --> x1.C does not equal to x2.C
x3 = ME.SparseTensor(x1.F * x2.F, coords=x1.C) 

# idea operation
x3 = x1 * x2
```

**Comment by BestSonny** [comment]
I am thinking one possibility where we sort the coordinate first and rearrange the features. Once the feature arrangements are the same between two sparse vectors, we can conduct the element-wise directly.

**Comment by chrischoy** [comment]
I see. That is a lot cleaner. Let me work on it.

**Comment by chrischoy** [comment]
The latest commit (https://github.com/StanfordVL/MinkowskiEngine/commit/2f9839622e6786ea2c91e1458bc963b60aa8a78f) resolved the issue.

I added a few basic operations on how to use it: 
https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/sparse_tensor_basic.py

**Comment by BestSonny** [comment]
@chrischoy  Thanks a lot.
