### ISSUE TITLE
utils.py file in a working directory breaks MinkowskiEngine

### ISSUE THREAD

**Issue by jac99** [StanfordVL/MinkowskiEngine#75]
It seems that a file named utils.py is in the current directory breaks MinkowskiEngine.

I've tried to train a network using MinkowskiEngine and got the following error:

> AttributeError: module 'utils' has no attribute 'kaiming_normal_'

It turns out that a file utils.py in the current direcctory conflicts with utils.py used by MinkowskiEngine. After renaming a local utils.py file everything starts to work fine.

**Comment by chrischoy** [comment]
Thanks for reporting the issue. I've added the scope for imports.
