### ISSUE TITLE
Segmentation fault when  calling SparseTensor() with coords and features tensors on CUDA.

### ISSUE THREAD

**Issue by jac99** [StanfordVL/MinkowskiEngine#76]
When calling SparseTensor() with coords and features tensors already on CUDA I got the following error:
..../anaconda3/envs/py3-mink/lib/python3.7/site-packages/MinkowskiEngine-0.3.3-py3.7-linux-x86_64.egg/MinkowskiEngine/SparseTensor.py:204: UserWarning: Coords implicitly converted to torch.IntTensor. To remove this warning, use `.int()` to convert the coords into an torch.IntTensor
  'To remove this warning, use `.int()` to convert the ' +
followed by **Segmentation fault**

I'm not sure if this is a bug or an intended behaviour (in such case, the error message should be more descriptive). Using SparseTensor() with coords and features on CPU and then moving the resultant SparseTensor to GPU works fine.

**Comment by chrischoy** [comment]
Thanks for reporting the issue.

I assume that coordinates are on CPU since all coordinate related operations are done on CPU right now (GPU coords man under development). I'll put assertions to check CPU coords values for the next commit.
