### ISSUE TITLE
Specifying C^out for the MinkowskiConvolution

### ISSUE THREAD

**Issue by whitealex95** [StanfordVL/MinkowskiEngine#77]
Hi,

In you documentation for minkowski convolution 
(link: https://stanfordvl.github.io/MinkowskiEngine/convolution.html)

The convolution is done to calculate the value of the specified output coordinates.
Is there a way to specify the output coordinates?
As far as I understand, I think that we can only have C^in be same as C^out when simply using the MinkowskiConvolution in your api

**Comment by chrischoy** [comment]
There an optional second argument for forward https://stanfordvl.github.io/MinkowskiEngine/convolution.html#MinkowskiEngine.MinkowskiConvolution.forward 

Also, theres an example https://github.com/StanfordVL/MinkowskiEngine/blob/master/tests/conv_on_coords.py#L74

**Comment by whitealex95** [comment]
Thank you for the information.
You're a life saver!
