### ISSUE TITLE
The function definition for the cat function seems to have changed

### ISSUE THREAD

**Issue by sjnarmstrong** [StanfordVL/MinkowskiEngine#78]
As shown here:
https://github.com/StanfordVL/MinkowskiEngine/blob/17640f161d926dac39a0f2a98b616cf4181025bd/MinkowskiEngine/MinkowskiOps.py#L49

The newer versions of ME make use of *sparce_tensors as opposed to a single tuple value.

The current models make use of the tuple definition

**Comment by chrischoy** [comment]
Thanks for reporting the issue. I've updated the documentation page and docstring on https://github.com/StanfordVL/MinkowskiEngine/commit/2727a7ddc4dea19b4783a0b5679f93eb175c579d
