### ISSUE TITLE
pytorch 1.4 bug issue

### ISSUE THREAD

**Issue by imransai** [StanfordVL/MinkowskiEngine#79]
Hello!

Recently, I installed the Minkowski Engine with pytorch 1.4 and cuda 10.1. The installation seems to be running well. But I soon found out a bug with pytorch 1.4 which is preventing me to use their gradient computation backward. I opened an issue in pytorch forum. The link is:
https://github.com/pytorch/pytorch/issues/32564.

I was able to resolve this problem by installing pytorch 1.4 nightly with cuda toolkit 10.1 (CUDA >=10.1). But now the Minkowski installation throws lots of errors. 
Some error examples:

error: no matching function for call to ‘boxAndCallBoxedFunc(void (* const&)(c10::OperatorKernel*, const c10::OperatorHandle&, c10::Stack*), c10::OperatorKernel*, const c10::OperatorHandle&, const at::Tensor&, const at::Tensor&, c10::ArrayRef<long int>, c10::ArrayRef<long int>)

I am assuming Minkowski Engine is not adaptable with pytorch 1.4 nightly.
Is there any way to adapt this Engine to pytorch 1.4 nightly or with lower versions of pytorch which is compatible with <= cuda 10.0 ?

**Comment by chrischoy** [comment]
I would recommend using pytorch 1.3 instead until they release the official upgrade.
For the last few version upgrades, they had some bugs, which they soon fixed with 1.x.1 version within a few weeks and had no problem with MinkowskiEngine afterward.

**Comment by imransai** [comment]
Installing Pytorch 1.3 with cudatoolkit 10.1 appears to solve this problem! Thanks!

**Comment by golnazhabibi3** [comment]
I have the same issue, how did you install Pytorch 1.3? I could not find it online

**Comment by chrischoy** [comment]
Something like
pip install torch==1.3.1

Or if you use conda
conda install pytorch==1.3.1 -c pytorch
