### ISSUE TITLE
Question regarding sparsity convolution

### ISSUE THREAD

**Issue by imransai** [StanfordVL/MinkowskiEngine#83]
Hi Chris,
Sorry for bugging you again! So I was planning to implement sparsity convolution from the paper: Sparse 3D convolutional neural network (link: https://arxiv.org/pdf/1505.02890.pdf ) using ME engine. 

![image](https://user-images.githubusercontent.com/9092769/73474892-38ab6e80-435d-11ea-81c2-caddc647aad1.png)

What the top image shows is that the active ouput coordinates will simply expand/dilate based on the kernel size/receptive field (2 x 2 in this case) applied the input active site. So the output coordinate will turn on if the receptive field of that coordinate covers any of the input active site. For my application, I would need to slowly densify the active sites (Sparse to Dense application) from sparse active sites as we go deep in the network. 

From my understanding, the default sparse convolution in ME engine performs a different variant of sparsity convolution, atleast not from the diagram you put in the link https://stanfordvl.github.io/MinkowskiEngine/convolution_on_sparse.html (please correct me if I am wrong). 

I was trying to use MinowskiConvolutionTranspose (with stride 1, so that it has same size as input) which seems to have generate_coordinates feature available that claims to generate output coordinates based on the 'outer product' of kernel shape and input coordinates, but it is throwing me some error like COORDS_KEY_DIFFERENT_ERROR.

The paper (link provided above) already seems to have an implementation available. But I would love to use ME engine since it offers a variety of features, and also highly efficient.

**Comment by chrischoy** [comment]
It works fine on this small example. I believe the error is not from the convolution transpose.

```python
import torch
import MinkowskiEngine as ME

channels = [3, 4]
coords = torch.IntTensor([[0, 0], [1, 0], [1, 1]])
feats = torch.rand(len(coords), channels[0])

coords, feats = ME.utils.sparse_collate([coords], [feats])

# Create a sparse tensor with large tensor strides for upsampling
input = ME.SparseTensor(
    feats,
    coords=coords)

conv_tr1 = ME.MinkowskiConvolutionTranspose(
    channels[0],
    channels[1],
    kernel_size=2,
    stride=1,
    generate_new_coords=True,
    dimension=2)

output = conv_tr1(input)
print(input.C)
print(output.C)
```
