### ISSUE TITLE
Questions about ModelNet40 classification.

### ISSUE THREAD

**Issue by SUZhaoyu** [StanfordVL/MinkowskiEngine#84]
Hi there, 

I tried to reproduce the results for ModelNet40 classification task, when I execute the code using `python -m examples.modelnet40 --batch_size 128 --stat_freq 100`, an error occurred:

> Traceback (most recent call last):
  File "/home/tan/anaconda2/envs/py3-mink/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tan/anaconda2/envs/py3-mink/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tan/MinkowskiEngine/examples/modelnet40.py", line 473, in <module>
    net = ResNet50(3, 40, D=3)
  File "/home/tan/MinkowskiEngine/examples/resnet.py", line 45, in __init__
    self.network_initialization(in_channels, out_channels, D)
  File "/home/tan/MinkowskiEngine/examples/resnet.py", line 72, in network_initialization
    self.glob_avg = ME.MinkowskiGlobalMaxPooling(dimension=D)
TypeError: __init__() got an unexpected keyword argument 'dimension'

So I have to convert the code `self.glob_avg = ME.MinkowskiGlobalMaxPooling(dimension=D)` into `self.glob_avg = ME.MinkowskiGlobalMaxPooling()`, and this time it works fine and the training begins. However, the validation results are quite poor: only around 70% accuracy, I'm not sure whether its due to my modification (I installed the Minkowski Engine using Anaconda following the instructions in the home page), would you please have a look if this is a bug or something? 

Btw, since ModelNet40 is a widely adopted dataset, it could not be better if you are able to provide the official benchmark for comparison, as it is not reported in your CVPR paper. Thanks in advance.

Regards,
Tony

**Comment by chrischoy** [comment]
Hi Tony,

Thanks for reporting the issue. It seems that I didn't update the example after some breaking changes. I remember getting test accuracy ~85% after some epochs, but I can run the example again.

This is a demo example to showcase how a training should be done using Minkowski Engine. I didn't mean to push any metrics, so you many need to increase the resolution, increase the sample density, tweak the data augmentation, and find the right hyper-parameters to push for the numbers to close to SOTA, which I haven't done, but I generally recommend everyone to work on a real dataset which I think is more interesting and is trainable on small GPUs using Minkowski Engine.

**Comment by SUZhaoyu** [comment]
Hi Chris,

Thank you for the reply, I got your point. Great works!
