### ISSUE TITLE
Please add a reminder about RAM usage of ModelNet40 classification demo

### ISSUE THREAD

**Issue by lilanxiao** [StanfordVL/MinkowskiEngine#86]
Hello,
 
thank you for sharing this amazing work! 

When I tried to run the ModelNet40 classification demo, my computer got stuck after some minutes of running and I had to use reisub to reboot it. The reason is that the ModelNet40Dataset caches the data set with the size of approximately 10G. Since my PC has only 16G RAM, it perhaps ran out of memory for running the demo. 

Would you please add a reminder in the documents? The memory usage might be ignored by some people and causes problems. 

In case other new users see this. Here is a reminder: be careful with the memory usage! 32G-RAM would be fine but 16G is really tough for this demo.

Best Regards
Lanxiao

**Comment by chrischoy** [comment]
Hi Lanxiao, thanks for the thoughtful note. I added the warning on the example as well as the main doc.
