### ISSUE TITLE
Installation error: fatal error: cublas_v2.h: No such file or directory

### ISSUE THREAD

**Issue by SwagJ** [StanfordVL/MinkowskiEngine#89]
Cuda Version: 10.1
Pytorch Version: 1.4.0
Ubuntu Version: 19.10
GCC Version: 7.3.0

I used conda installation method and with openblas installed and it gives me fatal error. 

Error Message Below: 

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Using openblas
CXX src/region.cpp
CXX src/pooling_global_max.cpp
CXX src/math_functions.cpp
CXX src/pooling_transpose.cpp
CXX src/pooling_global_avg.cpp
CXX src/robin_coordsmap.cpp
CXX src/union.cpp
CXX src/broadcast.cpp
CXX src/quantization.cpp
CXX src/coords_manager.cpp
CXX src/pooling_avg.cpp
CXX src/convolution_transpose.cpp
In file included from src/math_functions.hpp:29:0,
                 from src/math_functions.cpp:25:
src/gpu.cuh:28:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:162: objs/math_functions.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/gpu_memory_manager.hpp:8:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/pooling_transpose.cpp:25:
src/gpu.cuh:28:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
In file included from src/gpu_memory_manager.hpp:8:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/broadcast.cpp:25:
src/gpu.cuh:28:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
In file included from src/gpu_memory_manager.hpp:8:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/pooling_global_max.cpp:21:
src/gpu.cuh:28:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
In file included from src/gpu_memory_manager.hpp:8:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/pooling_avg.cpp:25:
src/gpu.cuh:28:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
In file included from src/gpu_memory_manager.hpp:8:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/convolution_transpose.cpp:25:
src/gpu.cuh:28:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
In file included from src/gpu_memory_manager.hpp:8:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/pooling_global_avg.cpp:25:
src/gpu.cuh:28:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
compilation terminated.
In file included from src/gpu_memory_manager.hpp:8:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/coords_manager.cpp:25:
src/gpu.cuh:28:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
In file included from src/gpu_memory_manager.hpp:8:0,
                 from src/coords_manager.hpp:46,
                 from src/common.hpp:34,
                 from src/union.hpp:28,
                 from src/union.cpp:25:
src/gpu.cuh:28:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
make: *** [Makefile:161: objs/pooling_transpose.o] Error 1
make: *** [Makefile:161: objs/broadcast.o] Error 1
make: *** [Makefile:161: objs/pooling_avg.o] Error 1
make: *** [Makefile:161: objs/coords_manager.o] Error 1
make: *** [Makefile:161: objs/convolution_transpose.o] Error 1
make: *** [Makefile:161: objs/pooling_global_avg.o] Error 1
make: *** [Makefile:161: objs/pooling_global_max.o] Error 1
make: *** [Makefile:161: objs/union.o] Error 1
running install
running bdist_egg
running egg_info
creating MinkowskiEngine.egg-info
writing MinkowskiEngine.egg-info/PKG-INFO
writing dependency_links to MinkowskiEngine.egg-info/dependency_links.txt
writing requirements to MinkowskiEngine.egg-info/requires.txt
writing top-level names to MinkowskiEngine.egg-info/top_level.txt
writing manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
reading manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/SparseTensor.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiOps.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiPruning.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiFunctional.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiBroadcast.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiCoords.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/Common.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiConvolution.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/__init__.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNormalization.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiPooling.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNetwork.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiUnion.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNonlinearity.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine
creating build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/collation.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/coords.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/init.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/quantization.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/__init__.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/gradcheck.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/utils
creating build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/senet_block.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/__init__.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/resnet_block.py -> build/lib.linux-x86_64-3.7/MinkowskiEngine/modules
running build_ext
building 'MinkowskiEngineBackend' extension
C compiler: gcc -pthread -B /disk_1/anaconda3/envs/fcgf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/pybind
compile options: '-I./ -I/disk_1/anaconda3/envs/fcgf/include/python3.7m/.. -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/TH -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/THC -I:/disk_1/cuda-10.1/include -I/disk_1/anaconda3/envs/fcgf/include/python3.7m -c'
extra options: '-Wno-deprecated-declarations -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MinkowskiEngineBackend -D_GLIBCXX_USE_CXX11_ABI=0'
gcc: pybind/minkowski.cpp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from ./src/gpu_memory_manager.hpp:8:0,
                 from ./src/coords_manager.hpp:46,
                 from ./src/common.hpp:34,
                 from pybind/extern.hpp:29,
                 from pybind/minkowski.cpp:32:
./src/gpu.cuh:28:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
error: Command "gcc -pthread -B /disk_1/anaconda3/envs/fcgf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./ -I/disk_1/anaconda3/envs/fcgf/include/python3.7m/.. -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/TH -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/THC -I:/disk_1/cuda-10.1/include -I/disk_1/anaconda3/envs/fcgf/include/python3.7m -c pybind/minkowski.cpp -o build/temp.linux-x86_64-3.7/pybind/minkowski.o -Wno-deprecated-declarations -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MinkowskiEngineBackend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11" failed with exit status 1
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by SwagJ** [comment]
fixed with correct setting of CUDA_HOME, but still have warnings during build? Will that matters? 

Typical Warning message below: 

/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/profiler.h(97): warning: attribute "__visibility__" does not apply here

/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(24): warning: integer conversion resulted in a change of sign

/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/enum.h(179): warning: statement is unreachable

creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/pybind
compile options: '-I./ -I/disk_1/anaconda3/envs/fcgf/include/python3.7m/.. -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/TH -I/disk_1/anaconda3/envs/fcgf/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/disk_1/anaconda3/envs/fcgf/include/python3.7m -c'
extra options: '-Wno-deprecated-declarations -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MinkowskiEngineBackend -D_GLIBCXX_USE_CXX11_ABI=0'
gcc: pybind/minkowski.cpp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

**Comment by chrischoy** [comment]
Glad it worked.
The warnings seem typical warnings that I also get. These warnings originate from pytorch source codes and are intended if you use any pytorch cpp extensions.

**Comment by Nitinmlp** [comment]
I am getting same issue in different context. The file exists in 3 different locations on my system. I modified INCPATH and it did not work. I even gave absolute path of the file in the header file and still it does not work. any ideas what could be causing such issue?

and why this particular file. I f google, I see many in dev community complaining about this issue in different compilation contexts.
$find /usr/local -name "cublas.h"
/usr/local/cuda-8.0/include/cublas.h
/usr/local/cuda-10.0/include/cublas.h
/usr/local/cuda-10.1/targets/x86_64-linux/include/cublas.h

$find /usr/include -name "cublas.h"
/usr/include/cublas.h

In /plugin/decoderPlugin.h

#ifndef GNMT_DECODER_PLUGIN_H
#define GNMT_DECODER_PLUGIN_H

#include <NvInfer.h>
#include "NvInferPlugin.h"
#Compilation failing use absolute path for cublas_v2.h and it still fails
#include "/usr/include/cublas_v2.h"
#include <cublasLt.h>

Failure Log:
In file included from plugin/decoderPlugin.cu:19:0:
plugin/decoderPlugin.h:22:36: fatal error: /usr/include/cublas_v2.h: No such file or directory
compilation terminated.
Makefile:137: recipe for target '../../../../build/bin/GNMT/chobj/plugin/decoderPlugin.o' failed
make[2]: *** [../../../../build/bin/GNMT/chobj/plugin/decoderPlugin.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by chrischoy** [comment]
```
cd /usr/local/
sudo ln -s cuda-10.1 cuda
export CUDA_HOME=/usr/local/cuda # pytorch uses this environment variable for cuda headers, shared libs
cd /path/to/minkowskiengine
python setup.py install
```

**Comment by Nitinmlp** [comment]
Chris this is not helping.

BTW Although I have reported this error here I am trying to build MLPerf V05 Closed Nvidia (build_docker)

ubuntu-sys:/usr/local/cuda> pwd
/usr/local/cuda-10.1

/MlPerf/V05/inference_results_v0.5/closed/NVIDIA$ export CUDA_HOME=/usr/local/cuda
@ubuntu-sys:/Myhome/MlPerf/V05/inference_results_v0.5/closed/NVIDIA$ echo $CUDA_HOME
/usr/local/cuda
nitin@ubuntu-sys:/Myhome/MlPerf/V05/inference_results_v0.5/closed/NVIDIA$ make build_docker

Building Docker image
docker build -t mlperf-inference:nitinv-latest \
        --network host -f docker/Dockerfile .
Sending build context to Docker daemon  3.758MB
Step 1/33 : ARG BASE_IMAGE=nvcr.io/nvidia/tensorrt:19.09-py3
Step 2/33 : FROM ${BASE_IMAGE}
...
...

Step 32/33 : RUN cd /work && make build
 ---> Running in b7b3814d1da0
Cloning Official MLPerf Inference (For Loadgen Files)
..
..
Building GNMT source...
cd code/gnmt/tensorrt/src \
        && make -j
make[2]: Entering directory '/work/code/gnmt/tensorrt/src'
Compiling: plugin/attentionPlugin.cpp
Compiling: core/GNMTBeamSearch.cpp
Compiling: core/params.cpp
Compiling: core/GNMTDecoder.cpp
Compiling: core/BatchSequencer.cpp
Compiling: core/GNMTEncoder.cpp
Compiling: core/GNMTEncoder.cpp
Compiling: core/GNMTDecoder.cpp
Compiling: core/BatchStream.cpp
Compiling: core/BatchSequencer.cpp
Compiling: plugin/GNMTScorerPlugin.cpp
Compiling: core/GNMTEngine.cpp
Compiling: core/GNMTCore.cpp
Compiling: plugin/dumpTensorPlugin.cpp
Compiling: core/BatchStream.cpp
Compiling: core/GNMTGenerator.cpp
Compiling: core/GNMTQuery.cpp
Compiling: core/GNMTAttention.cpp
Compiling: plugin/GNMTScorerPlugin.cpp
Compiling: core/GNMTEngine.cpp
Compiling: core/utils.cpp
Compiling: core/GNMTScorer.cpp
Compiling: plugin/attentionPlugin.cpp
Compiling: core/GNMTScorer.cpp
Compiling: core/GNMTCore.cpp
Compiling: core/params.cpp
Compiling: plugin/multiGatherPlugin.cpp
Compiling: core/GNMTQuery.cpp
Compiling: core/GNMTIndexer.cpp
Compiling: core/GNMTGenerator.cpp
Compiling: core/GNMTIndexer.cpp
Compiling: core/GNMTBeamSearch.cpp
Compiling: core/GNMTAttention.cpp​
Compiling: core/GNMTShuffler.cpp
Compiling: core/GNMTShuffler.cpp
Compiling: plugin/dumpTensorPlugin.cpp
Compiling: plugin/multiGatherPlugin.cpp
Compiling: core/utils.cpp
In file included from plugin/decoderPlugin.cu:19:0:
plugin/decoderPlugin.h:22:23: fatal error: cublas_v2.h: No such file or directory
compilation terminated.
Makefile:144: recipe for target '../../../../build/bin/GNMT/dchobj/plugin/decoderPlugin.o' failed
make[2]: *** [../../../../build/bin/GNMT/dchobj/plugin/decoderPlugin.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from plugin/decoderPlugin.cu:19:0:
plugin/decoderPlugin.h:22:23: fatal error: cublas_v2.h: No such file or directory
compilation terminated.
Makefile:137: recipe for target '../../../../build/bin/GNMT/chobj/plugin/decoderPlugin.o' failed
make[2]: *** [../../../../build/bin/GNMT/chobj/plugin/decoderPlugin.o] Error 1

As I stated earlier:
I have atleast 4 dir in which cublas_v2.h file is there. Even if I edit plugin/decoderPlugin.h:22:23:
and give absolute path of the file, it still complains that it cannot find the cublas_v2.h file. If I comment out the include stmet. it complains same issue about: #include <cublasLt.h>

Regards
Nitin

________________________________
