### ISSUE TITLE
Error when run example.py

### ISSUE THREAD

**Issue by TWJianNuo** [StanfordVL/MinkowskiEngine#9]
I follow the installation instruction which goes smoothly. Then while I try to run example.py, an error reported. Below is the error message:

`Traceback (most recent call last):
  File "examples/example.py", line 28, in <module>
    import MinkowskiEngine as ME
  File "/media/shengjie/other/IndoorSemanticIns/MinkowskiEngine/MinkowskiEngine/__init__.py", line 35, in <module>
    from SparseTensor import SparseTensor
  File "/media/shengjie/other/IndoorSemanticIns/MinkowskiEngine/MinkowskiEngine/SparseTensor.py", line 29, in <module>
    from MinkowskiCoords import CoordsKey, CoordsManager
  File "/media/shengjie/other/IndoorSemanticIns/MinkowskiEngine/MinkowskiEngine/MinkowskiCoords.py", line 27, in <module>
    import MinkowskiEngineBackend as MEB
ImportError: /home/shengjie/anaconda3/envs/py36/lib/python3.6/site-packages/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg/MinkowskiEngineB`

It's quite similar to the issue #1, but slightly different. I really appreciate if you can resolve the issue.

**Comment by chrischoy** [comment]
It doesn’t look like the engine is complied correctly. Can you type make and put the result here?

**Comment by TWJianNuo** [comment]
I type "make" under the "MinkowskiEngine" folder and get:
"rm -f -rf build dist".

I type "make clean" and re-execute "python setup.py install", get:

`
CXX src/thread_pool.cpp
CXX src/pooling_global.cpp
CXX src/convolution_transpose.cpp
CXX src/convolution.cpp
CXX src/coords_manager.cpp
CXX src/broadcast.cpp
CXX src/voxelization.cpp
CXX src/pooling_avg.cpp
CXX src/math_functions.cpp
CXX src/region_iter.cpp
CXX src/pooling_transpose.cpp
CXX src/coords_key.cpp
CXX src/pooling_max.cpp
CXX src/pruning.cpp
NVCC src/broadcast.cu
NVCC src/voxelization.cu
NVCC src/pruning.cu
NVCC src/pooling_avg.cu
NVCC src/math_functions.cu
NVCC src/gpu.cu
NVCC src/pooling_max.cu
NVCC src/convolution.cu
rm -f -f ./objs/libminkowski.a
LD -o objs/libminkowski.a
ar rc ./objs/libminkowski.a ./objs/thread_pool.o ./objs/pooling_global.o ./objs/convolution_transpose.o ./objs/convolution.o ./objs/coords_manager.o ./objs/broadcast.o ./objs/voxelization.o ./objs/pooling_avg.o ./objs/math_functions.o ./objs/region_iter.o ./objs/pooling_transpose.o ./objs/coords_key.o ./objs/pooling_max.o ./objs/pruning.o ./objs/cuda/broadcast.o ./objs/cuda/voxelization.o ./objs/cuda/pruning.o ./objs/cuda/pooling_avg.o ./objs/cuda/math_functions.o ./objs/cuda/gpu.o ./objs/cuda/pooling_max.o ./objs/cuda/convolution.o
# @g++ -o objs/libminkowski.a ./objs/thread_pool.o ./objs/pooling_global.o ./objs/convolution_transpose.o ./objs/convolution.o ./objs/coords_manager.o ./objs/broadcast.o ./objs/voxelization.o ./objs/pooling_avg.o ./objs/math_functions.o ./objs/region_iter.o ./objs/pooling_transpose.o ./objs/coords_key.o ./objs/pooling_max.o ./objs/pruning.o ./objs/cuda/broadcast.o ./objs/cuda/voxelization.o ./objs/cuda/pruning.o ./objs/cuda/pooling_avg.o ./objs/cuda/math_functions.o ./objs/cuda/gpu.o ./objs/cuda/pooling_max.o ./objs/cuda/convolution.o -pthread -fPIC -Wall -Wno-sign-compare -Wcomment -Wl,-rpath= -Wl,--no-as-needed -Wl,--sysroot=/ -L/usr/local/cuda/lib64 -lstdc++ -lcudart -lcublas -lc10 -lcaffe2 -ltorch -ltorch_python -lcaffe2_gpu -lopenblas
rm -f -rf build dist
running install
running bdist_egg
running egg_info
writing MinkowskiEngine.egg-info/PKG-INFO
writing dependency_links to MinkowskiEngine.egg-info/dependency_links.txt
writing requirements to MinkowskiEngine.egg-info/requires.txt
writing top-level names to MinkowskiEngine.egg-info/top_level.txt
reading manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
writing manifest file 'MinkowskiEngine.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiPruning.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNormalization.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/SparseTensor.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiOps.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiCoords.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiBroadcast.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/Common.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNetwork.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiNonlinearity.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiPooling.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiFunctional.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/MinkowskiConvolution.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
copying ./MinkowskiEngine/__init__.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine
creating build/lib.linux-x86_64-3.6/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/voxelization.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/collation.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/__init__.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine/utils
copying ./MinkowskiEngine/utils/gradcheck.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine/utils
creating build/lib.linux-x86_64-3.6/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/resnet_block.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/senet_block.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine/modules
copying ./MinkowskiEngine/modules/__init__.py -> build/lib.linux-x86_64-3.6/MinkowskiEngine/modules
running build_ext
building 'MinkowskiEngineBackend' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/pybind
gcc -pthread -B /home/shengjie/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./ -I/home/shengjie/anaconda3/envs/py36/include/python3.6m/.. -I/home/shengjie/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include -I/home/shengjie/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/shengjie/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/TH -I/home/shengjie/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/shengjie/anaconda3/envs/py36/include/python3.6m -c pybind/minkowski.cpp -o build/temp.linux-x86_64-3.6/pybind/minkowski.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MinkowskiEngineBackend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/shengjie/anaconda3/envs/py36/compiler_compat -L/home/shengjie/anaconda3/envs/py36/lib -Wl,-rpath=/home/shengjie/anaconda3/envs/py36/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/pybind/minkowski.o -Lobjs -L/usr/local/cuda/lib64 -lminkowski -lopenblas -lcudart -o build/lib.linux-x86_64-3.6/MinkowskiEngineBackend.cpython-36m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/MinkowskiPruning.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
creating build/bdist.linux-x86_64/egg/MinkowskiEngine/modules
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/modules/resnet_block.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine/modules
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/modules/senet_block.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine/modules
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/modules/__init__.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine/modules
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/MinkowskiNormalization.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/SparseTensor.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/MinkowskiOps.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/MinkowskiCoords.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/MinkowskiBroadcast.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/Common.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/MinkowskiNetwork.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/MinkowskiNonlinearity.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
creating build/bdist.linux-x86_64/egg/MinkowskiEngine/utils
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/utils/voxelization.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine/utils
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/utils/collation.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine/utils
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/utils/__init__.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine/utils
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/utils/gradcheck.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine/utils
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/MinkowskiPooling.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/MinkowskiFunctional.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/MinkowskiConvolution.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngine/__init__.py -> build/bdist.linux-x86_64/egg/MinkowskiEngine
copying build/lib.linux-x86_64-3.6/MinkowskiEngineBackend.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/MinkowskiPruning.py to MinkowskiPruning.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/modules/resnet_block.py to resnet_block.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/modules/senet_block.py to senet_block.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/modules/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/MinkowskiNormalization.py to MinkowskiNormalization.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/SparseTensor.py to SparseTensor.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/MinkowskiOps.py to MinkowskiOps.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/MinkowskiCoords.py to MinkowskiCoords.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/MinkowskiBroadcast.py to MinkowskiBroadcast.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/Common.py to Common.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/MinkowskiNetwork.py to MinkowskiNetwork.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/MinkowskiNonlinearity.py to MinkowskiNonlinearity.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/utils/voxelization.py to voxelization.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/utils/collation.py to collation.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/utils/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/utils/gradcheck.py to gradcheck.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/MinkowskiPooling.py to MinkowskiPooling.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/MinkowskiFunctional.py to MinkowskiFunctional.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/MinkowskiConvolution.py to MinkowskiConvolution.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngine/__init__.py to __init__.cpython-36.pyc
creating stub loader for MinkowskiEngineBackend.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/MinkowskiEngineBackend.py to MinkowskiEngineBackend.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying MinkowskiEngine.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying MinkowskiEngine.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying MinkowskiEngine.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying MinkowskiEngine.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying MinkowskiEngine.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying MinkowskiEngine.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg
removing '/home/shengjie/anaconda3/envs/py36/lib/python3.6/site-packages/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg' (and everything under it)
creating /home/shengjie/anaconda3/envs/py36/lib/python3.6/site-packages/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg
Extracting MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg to /home/shengjie/anaconda3/envs/py36/lib/python3.6/site-packages
MinkowskiEngine 0.2.4 is already the active version in easy-install.pth

Installed /home/shengjie/anaconda3/envs/py36/lib/python3.6/site-packages/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg
Processing dependencies for MinkowskiEngine==0.2.4
Searching for torch==1.0.1
Best match: torch 1.0.1
Adding torch 1.0.1 to easy-install.pth file
Installing convert-caffe2-to-onnx script to /home/shengjie/anaconda3/envs/py36/bin
Installing convert-onnx-to-caffe2 script to /home/shengjie/anaconda3/envs/py36/bin

Using /home/shengjie/anaconda3/envs/py36/lib/python3.6/site-packages
Finished processing dependencies for MinkowskiEngine==0.2.4
`

**Comment by chrischoy** [comment]
It seems that it is installed. Could you update your first comment to include the rest of the error message when you run the example?

**Comment by chrischoy** [comment]
The error message is incomplete and no response after it is compiled. Ill assume that the problem has been resolved.

**Comment by TWJianNuo** [comment]
Sorry I update late, the updated message is listed below:
`Traceback (most recent call last):
  File "/media/shengjie/other/IndoorSemanticIns/MinkowskiEngine/examples/example.py", line 28, in <module>
    import MinkowskiEngine as ME
  File "/media/shengjie/other/IndoorSemanticIns/MinkowskiEngine/MinkowskiEngine/__init__.py", line 35, in <module>
    from SparseTensor import SparseTensor
  File "/media/shengjie/other/IndoorSemanticIns/MinkowskiEngine/MinkowskiEngine/SparseTensor.py", line 29, in <module>
    from MinkowskiCoords import CoordsKey, CoordsManager
  File "/media/shengjie/other/IndoorSemanticIns/MinkowskiEngine/MinkowskiEngine/MinkowskiCoords.py", line 27, in <module>
    import MinkowskiEngineBackend as MEB
ImportError: /home/shengjie/anaconda3/envs/py36/lib/python3.6/site-packages/MinkowskiEngine-0.2.4-py3.6-linux-x86_64.egg/MinkowskiEngineBackend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE`

There is another weired issue, that the compiled file is installed inside environment "py36" rather than creted environment "py3-mink".

I spend time working on how to print complete error message due to my pdb is not set correctly. Then I seek to pycharm, where I find compiled module is missing(as it is installed inside py36 environment). Then Spend some time to fix the issue, and make the late response.

Sorry again.

**Comment by TWJianNuo** [comment]
Oh, I find out I didn't copy-paste complete error message. It's so awkward...

**Comment by chrischoy** [comment]
I see. It seems like the shared library is not linked correctly. Could you send an email to chrischoy@ai.stanford.edu?

**Comment by TWJianNuo** [comment]
Sure. Thanks.

**Comment by chrischoy** [comment]
This seems related to https://github.com/NVIDIA/flownet2-pytorch/issues/136

**Comment by TWJianNuo** [comment]
Hi, I somehow fixed it. I follow the instructions again in "py36" environment and recompile it in "py3-mink" environment. Then it works....

I send a report email to the chrischoy@ai.stanford.edu regarding problem description and fix procedure

**Comment by chrischoy** [comment]
Glad that you solved it and thanks for the follow up.

I think this was a pytorch version problem. Current MinkowskiEngine assume pytorch version 1.1

The class `UndefinedTensorImpl` was moved around when upgrading pytorch v.1.0.1 to pytorch v.1.1

https://github.com/pytorch/pytorch/blob/v1.1.0/c10/core/UndefinedTensorImpl.cpp

Could you confirm that your `py3-mink` is using pytorch v1.1 instead of pytorch v1.0.1 in `py36` environment?

**Comment by TWJianNuo** [comment]
I checked pytorch environment and find that in "py3-mink" pytorch version is 1.1.0. Current "py36" environment pytorch version is also 1.1.0. It's quite possible(but I am not 100% sure) that an update occurred while I am executing instructions in "py36" environment. Then fixation of the issue can be explained with your argument.

**Comment by chrischoy** [comment]
From the installation log https://pastebin.com/bxfkEXj0, I can find that the environment `py36` had pytorch 1.0.1.

```
Searching for torch==1.0.1
Best match: torch 1.0.1
Adding torch 1.0.1 to easy-install.pth file
```

I'll add more clear requirement in the documentation.

For all future reference, please use `pytorch >= 1.1`
