### ISSUE TITLE
Different results between v0.28 and v0.41

### ISSUE THREAD

**Issue by WilliamKRobert** [StanfordVL/MinkowskiEngine#91]
I got different results after I upgrade your library. I am using exactly the same code though. Could you point out what component changes might be?

**Comment by chrischoy** [comment]
The most significant change would be how we put batch indices. https://stanfordvl.github.io/MinkowskiEngine/sparse_tensor.html#MinkowskiEngine.SparseTensor.SparseTensor

If you directly manipulated the coordinates during data generation, this would the the source of the error.

To generate batched coordinates, please use `ME.utils.batched_coordinates(list of coordinates)`. To generate aligend coords, feats, labels, use `ME.utils.sparse_collate`  https://stanfordvl.github.io/MinkowskiEngine/utils.html#MinkowskiEngine.utils.sparse_collate.
