### ISSUE TITLE
Questions about the input of sparse convolution

### ISSUE THREAD

**Issue by baifanxxx** [StanfordVL/MinkowskiEngine#96]
Hi,
I‘m sorry to bother you. I have a doubt that the input of a sparse convolution should be a sparse tensor. However, if the dense tensor and the sparse tensor are concated, can the mixed tensor be obtained using sparse convolution to continue the operation?

**Comment by chrischoy** [comment]
I can't understand what you are trying to say.

`MinkowskiConvolution` can only process `SparseTensor`. If you concatenate dense tensor with sparse tensor and the support of the dense tensor covers the support of the sparse tensor, then you do not need to use `SparseTensor` to represent the output.
